# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage/v1/storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage/v1/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18storage/v1/storage.proto\x12\nstorage.v1\"T\n\x16GetPresignedUrlRequest\x12\x12\n\nobject_key\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x16\n\x0e\x65xpiration_sec\x18\x03 \x01(\x05\"&\n\x17GetPresignedUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\")\n\x13\x44\x65leteObjectRequest\x12\x12\n\nobject_key\x18\x01 \x01(\t\"8\n\x14\x44\x65leteObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbf\x01\n\x0eStorageService\x12Z\n\x0fGetPresignedUrl\x12\".storage.v1.GetPresignedUrlRequest\x1a#.storage.v1.GetPresignedUrlResponse\x12Q\n\x0c\x44\x65leteObject\x12\x1f.storage.v1.DeleteObjectRequest\x1a .storage.v1.DeleteObjectResponseB0\n\x1eme.unbrdn.core.grpc.storage.v1B\x0cStorageProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage.v1.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036me.unbrdn.core.grpc.storage.v1B\014StorageProtoP\001'
  _globals['_GETPRESIGNEDURLREQUEST']._serialized_start=40
  _globals['_GETPRESIGNEDURLREQUEST']._serialized_end=124
  _globals['_GETPRESIGNEDURLRESPONSE']._serialized_start=126
  _globals['_GETPRESIGNEDURLRESPONSE']._serialized_end=164
  _globals['_DELETEOBJECTREQUEST']._serialized_start=166
  _globals['_DELETEOBJECTREQUEST']._serialized_end=207
  _globals['_DELETEOBJECTRESPONSE']._serialized_start=209
  _globals['_DELETEOBJECTRESPONSE']._serialized_end=265
  _globals['_STORAGESERVICE']._serialized_start=268
  _globals['_STORAGESERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
