// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: common/v1/enums.proto

/* eslint-disable */

export const protobufPackage = "common.v1";

/** 인터뷰 단계 */
export enum InterviewStageProto {
  INTERVIEW_STAGE_UNSPECIFIED = 0,
  /** WAITING - 대기 (초기 상태) */
  WAITING = 1,
  /** GREETING - 면접관 인사 (사전 녹음) */
  GREETING = 2,
  /** CANDIDATE_GREETING - 지원자 첫 인사 감지 */
  CANDIDATE_GREETING = 3,
  /** INTERVIEWER_INTRO - 면접관 자기소개 (LLM) */
  INTERVIEWER_INTRO = 4,
  /** SELF_INTRO_PROMPT - 1분 자기소개 요청 (사전 녹음) */
  SELF_INTRO_PROMPT = 5,
  /** SELF_INTRO - 지원자 1분 자기소개 */
  SELF_INTRO = 6,
  /** IN_PROGRESS_STAGE - 본 면접 진행 */
  IN_PROGRESS_STAGE = 7,
  /** LAST_QUESTION_PROMPT - 마지막 질문 안내 (사전 녹음) */
  LAST_QUESTION_PROMPT = 8,
  /** LAST_ANSWER - 지원자 마지막 답변 */
  LAST_ANSWER = 9,
  /** CLOSING_GREETING - 면접관 마무리 인사 */
  CLOSING_GREETING = 11,
  /** COMPLETED_STAGE - 면접 완료 */
  COMPLETED_STAGE = 10,
  UNRECOGNIZED = -1,
}

/** 면접관 역할 */
export enum InterviewRoleProto {
  INTERVIEW_ROLE_UNSPECIFIED = 0,
  /** TECH - 기술 면접관 */
  TECH = 1,
  /** HR - 인사/컬처 면접관 */
  HR = 2,
  /** LEADER - 리드 면접관 */
  LEADER = 3,
  /** EXEC - 임원 면접관 */
  EXEC = 4,
  UNRECOGNIZED = -1,
}

/** 면접 차수/유형 (Round) */
export enum InterviewRoundProto {
  INTERVIEW_ROUND_UNSPECIFIED = 0,
  /** TECHNICAL_ROUND - 1차 면접 (기술 중심) */
  TECHNICAL_ROUND = 1,
  /** CULTURE_ROUND - 2차 면접 (인적성/컬쳐핏 중심) */
  CULTURE_ROUND = 2,
  /** EXECUTIVE_ROUND - 임원 면접 (전략/비전 중심) */
  EXECUTIVE_ROUND = 3,
  UNRECOGNIZED = -1,
}

/** 면접 분위기/성향 */
export enum InterviewPersonalityProto {
  INTERVIEW_PERSONALITY_UNSPECIFIED = 0,
  /** PRESSURE - 압박 면접 */
  PRESSURE = 1,
  /** COMFORTABLE - 편안한 분위기 */
  COMFORTABLE = 2,
  /** RANDOM - 랜덤 */
  RANDOM = 3,
  UNRECOGNIZED = -1,
}

/** 면접 세션 상태 */
export enum InterviewStatusProto {
  INTERVIEW_STATUS_UNSPECIFIED = 0,
  /** READY - 준비됨 */
  READY = 1,
  /** IN_PROGRESS - 진행 중 */
  IN_PROGRESS = 2,
  /** PAUSED - 중지됨 */
  PAUSED = 5,
  /** COMPLETED - 완료됨 */
  COMPLETED = 3,
  /** CANCELLED - 취소됨 */
  CANCELLED = 4,
  UNRECOGNIZED = -1,
}

/** 실시간 턴 상태 */
export enum InterviewTurnStatusProto {
  INTERVIEW_TURN_STATUS_UNSPECIFIED = 0,
  TURN_READY = 1,
  LISTENING = 2,
  THINKING = 3,
  SPEAKING = 4,
  TURN_PAUSED = 5,
  TURN_COMPLETED = 6,
  TURN_CANCELLED = 7,
  UNRECOGNIZED = -1,
}

/** 면접 유형 */
export enum InterviewTypeProto {
  INTERVIEW_TYPE_UNSPECIFIED = 0,
  /** REAL - 실전 */
  REAL = 1,
  /** PRACTICE - 연습 */
  PRACTICE = 2,
  UNRECOGNIZED = -1,
}

export const COMMON_V1_PACKAGE_NAME = "common.v1";
