# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/enums.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/enums.proto\x12\tcommon.v1*\x94\x02\n\x13InterviewStageProto\x12\x1f\n\x1bINTERVIEW_STAGE_UNSPECIFIED\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0c\n\x08GREETING\x10\x02\x12\x16\n\x12\x43\x41NDIDATE_GREETING\x10\x03\x12\x15\n\x11INTERVIEWER_INTRO\x10\x04\x12\x15\n\x11SELF_INTRO_PROMPT\x10\x05\x12\x0e\n\nSELF_INTRO\x10\x06\x12\x15\n\x11IN_PROGRESS_STAGE\x10\x07\x12\x18\n\x14LAST_QUESTION_PROMPT\x10\x08\x12\x0f\n\x0bLAST_ANSWER\x10\t\x12\x14\n\x10\x43LOSING_GREETING\x10\x0b\x12\x13\n\x0f\x43OMPLETED_STAGE\x10\n*R\n\x12InterviewRoleProto\x12\x1e\n\x1aINTERVIEW_ROLE_UNSPECIFIED\x10\x00\x12\x08\n\x04TECH\x10\x01\x12\x06\n\x02HR\x10\x02\x12\n\n\x06LEADER\x10\x03*m\n\x19InterviewPersonalityProto\x12%\n!INTERVIEW_PERSONALITY_UNSPECIFIED\x10\x00\x12\x0c\n\x08PRESSURE\x10\x01\x12\x0f\n\x0b\x43OMFORTABLE\x10\x02\x12\n\n\x06RANDOM\x10\x03*~\n\x14InterviewStatusProto\x12 \n\x1cINTERVIEW_STATUS_UNSPECIFIED\x10\x00\x12\t\n\x05READY\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x12\n\n\x06PAUSED\x10\x05\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04*L\n\x12InterviewTypeProto\x12\x1e\n\x1aINTERVIEW_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04REAL\x10\x01\x12\x0c\n\x08PRACTICE\x10\x02\x42\x33\n\x1dme.unbrdn.core.grpc.common.v1B\x10\x43ommonEnumsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035me.unbrdn.core.grpc.common.v1B\020CommonEnumsProtoP\001'
  _globals['_INTERVIEWSTAGEPROTO']._serialized_start=37
  _globals['_INTERVIEWSTAGEPROTO']._serialized_end=313
  _globals['_INTERVIEWROLEPROTO']._serialized_start=315
  _globals['_INTERVIEWROLEPROTO']._serialized_end=397
  _globals['_INTERVIEWPERSONALITYPROTO']._serialized_start=399
  _globals['_INTERVIEWPERSONALITYPROTO']._serialized_end=508
  _globals['_INTERVIEWSTATUSPROTO']._serialized_start=510
  _globals['_INTERVIEWSTATUSPROTO']._serialized_end=636
  _globals['_INTERVIEWTYPEPROTO']._serialized_start=638
  _globals['_INTERVIEWTYPEPROTO']._serialized_end=714
# @@protoc_insertion_point(module_scope)
