// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: interview/v1/interview.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  InterviewPersonalityProto,
  InterviewRoleProto,
  InterviewStageProto,
  InterviewStatusProto,
  InterviewTypeProto,
} from "../../common/v1/enums";

export const protobufPackage = "interview.v1";

/** === 메시지 정의 (DTO) === */
export interface CreateInterviewRequest {
  /** UUID */
  userId: string;
  /** UUID (optional - 이력서 없이도 면접 가능) */
  resumeId?: string | undefined;
  domain: string;
  type: InterviewTypeProto;
  /** 복수 선택 가능 (New) */
  interviewerRoles: InterviewRoleProto[];
  /** 면접 분위기 (New) */
  personality: InterviewPersonalityProto;
  targetDurationMinutes: number;
  selfIntroduction: string;
  interviewerCount: number;
}

export interface CreateInterviewResponse {
  /** UUID */
  interviewId: string;
  status: InterviewStatusProto;
}

/** Stage 조회 */
export interface GetInterviewStageRequest {
  interviewSessionId: string;
}

export interface GetInterviewStageResponse {
  stage: InterviewStageProto;
  selfIntroElapsedSeconds: number;
  persona?: string | undefined;
  interviewerCount?: number | undefined;
  domain?: string | undefined;
  selfIntroRetryCount: number;
  interviewerRoles: InterviewRoleProto[];
  personality: InterviewPersonalityProto;
}

/** Stage 전환 */
export interface TransitionStageRequest {
  interviewSessionId: string;
  newStage: InterviewStageProto;
}

export interface TransitionStageResponse {
  currentStage: InterviewStageProto;
}

/** 자기소개 재시도 증분 */
export interface IncrementSelfIntroRetryRequest {
  interviewSessionId: string;
}

export interface IncrementSelfIntroRetryResponse {
  newRetryCount: number;
}

/** 면접 목록 조회 */
export interface ListInterviewsRequest {
  /** UUID */
  userId: string;
}

export interface InterviewSessionSummary {
  interviewId: string;
  /** ISO 8601 */
  startedAt: string;
  status: InterviewStatusProto;
  domain: string;
  type: InterviewTypeProto;
  targetDurationMinutes: number;
  interviewerCount: number;
}

export interface ListInterviewsResponse {
  interviews: InterviewSessionSummary[];
}

export const INTERVIEW_V1_PACKAGE_NAME = "interview.v1";

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceClient {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(request: CreateInterviewRequest, metadata?: Metadata): Observable<CreateInterviewResponse>;

  /** Stage 관리 */

  getInterviewStage(request: GetInterviewStageRequest, metadata?: Metadata): Observable<GetInterviewStageResponse>;

  transitionStage(request: TransitionStageRequest, metadata?: Metadata): Observable<TransitionStageResponse>;

  /** 자기소개 재시도 제어 */

  incrementSelfIntroRetry(
    request: IncrementSelfIntroRetryRequest,
    metadata?: Metadata,
  ): Observable<IncrementSelfIntroRetryResponse>;

  /** 면접 목록 조회 */

  listInterviews(request: ListInterviewsRequest, metadata?: Metadata): Observable<ListInterviewsResponse>;
}

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceController {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(
    request: CreateInterviewRequest,
    metadata?: Metadata,
  ): Promise<CreateInterviewResponse> | Observable<CreateInterviewResponse> | CreateInterviewResponse;

  /** Stage 관리 */

  getInterviewStage(
    request: GetInterviewStageRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewStageResponse> | Observable<GetInterviewStageResponse> | GetInterviewStageResponse;

  transitionStage(
    request: TransitionStageRequest,
    metadata?: Metadata,
  ): Promise<TransitionStageResponse> | Observable<TransitionStageResponse> | TransitionStageResponse;

  /** 자기소개 재시도 제어 */

  incrementSelfIntroRetry(
    request: IncrementSelfIntroRetryRequest,
    metadata?: Metadata,
  ):
    | Promise<IncrementSelfIntroRetryResponse>
    | Observable<IncrementSelfIntroRetryResponse>
    | IncrementSelfIntroRetryResponse;

  /** 면접 목록 조회 */

  listInterviews(
    request: ListInterviewsRequest,
    metadata?: Metadata,
  ): Promise<ListInterviewsResponse> | Observable<ListInterviewsResponse> | ListInterviewsResponse;
}

export function InterviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createInterview",
      "getInterviewStage",
      "transitionStage",
      "incrementSelfIntroRetry",
      "listInterviews",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERVIEW_SERVICE_NAME = "InterviewService";
