// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: resume/v1/resume.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "resume.v1";

export interface GetUploadUrlRequest {
  userId: string;
  fileName: string;
  title: string;
}

export interface GetUploadUrlResponse {
  uploadUrl: string;
  resumeId: string;
}

export interface CompleteUploadRequest {
  resumeId: string;
  validationText: string;
  embedding: number[];
  existingResumeId?: string | undefined;
}

export interface CompleteUploadResponse {
  success: boolean;
  resume?: ResumeDetail | undefined;
}

export interface ListResumesRequest {
  userId: string;
}

export interface ResumeItem {
  id: string;
  title: string;
  status: string;
  createdAt: string;
  embedding: number[];
}

export interface ListResumesResponse {
  resumes: ResumeItem[];
}

export interface GetResumeRequest {
  resumeId: string;
  userId: string;
}

export interface ResumeDetail {
  id: string;
  title: string;
  content: string;
  status: string;
  createdAt: string;
  fileUrl: string;
}

export interface GetResumeResponse {
  resume?: ResumeDetail | undefined;
}

export interface DeleteResumeRequest {
  resumeId: string;
  userId: string;
}

export interface DeleteResumeResponse {
  success: boolean;
}

export interface ValidateResumeRequest {
  text: string;
}

export interface ValidateResumeResponse {
  isResume: boolean;
  reason: string;
  score: number;
}

export interface GetResumeChunksRequest {
  resumeId: string;
  limit: number;
}

export interface GetResumeChunksResponse {
  chunks: string[];
}

export const RESUME_V1_PACKAGE_NAME = "resume.v1";

export interface ResumeServiceClient {
  /** 이력서 업로드 URL 발급 */

  getUploadUrl(request: GetUploadUrlRequest, metadata?: Metadata): Observable<GetUploadUrlResponse>;

  /** 업로드 완료 확인 및 메타데이터 저장 */

  completeUpload(request: CompleteUploadRequest, metadata?: Metadata): Observable<CompleteUploadResponse>;

  /** 이력서 목록 조회 */

  listResumes(request: ListResumesRequest, metadata?: Metadata): Observable<ListResumesResponse>;

  /** 이력서 상세 조회 */

  getResume(request: GetResumeRequest, metadata?: Metadata): Observable<GetResumeResponse>;

  /** 이력서 삭제 */

  deleteResume(request: DeleteResumeRequest, metadata?: Metadata): Observable<DeleteResumeResponse>;

  /** 이력서 판별 (Valid / Invalid) */

  validateResume(request: ValidateResumeRequest, metadata?: Metadata): Observable<ValidateResumeResponse>;

  /** 이력서 청크 조회 (RAG 용) */

  getResumeChunks(request: GetResumeChunksRequest, metadata?: Metadata): Observable<GetResumeChunksResponse>;
}

export interface ResumeServiceController {
  /** 이력서 업로드 URL 발급 */

  getUploadUrl(
    request: GetUploadUrlRequest,
    metadata?: Metadata,
  ): Promise<GetUploadUrlResponse> | Observable<GetUploadUrlResponse> | GetUploadUrlResponse;

  /** 업로드 완료 확인 및 메타데이터 저장 */

  completeUpload(
    request: CompleteUploadRequest,
    metadata?: Metadata,
  ): Promise<CompleteUploadResponse> | Observable<CompleteUploadResponse> | CompleteUploadResponse;

  /** 이력서 목록 조회 */

  listResumes(
    request: ListResumesRequest,
    metadata?: Metadata,
  ): Promise<ListResumesResponse> | Observable<ListResumesResponse> | ListResumesResponse;

  /** 이력서 상세 조회 */

  getResume(
    request: GetResumeRequest,
    metadata?: Metadata,
  ): Promise<GetResumeResponse> | Observable<GetResumeResponse> | GetResumeResponse;

  /** 이력서 삭제 */

  deleteResume(
    request: DeleteResumeRequest,
    metadata?: Metadata,
  ): Promise<DeleteResumeResponse> | Observable<DeleteResumeResponse> | DeleteResumeResponse;

  /** 이력서 판별 (Valid / Invalid) */

  validateResume(
    request: ValidateResumeRequest,
    metadata?: Metadata,
  ): Promise<ValidateResumeResponse> | Observable<ValidateResumeResponse> | ValidateResumeResponse;

  /** 이력서 청크 조회 (RAG 용) */

  getResumeChunks(
    request: GetResumeChunksRequest,
    metadata?: Metadata,
  ): Promise<GetResumeChunksResponse> | Observable<GetResumeChunksResponse> | GetResumeChunksResponse;
}

export function ResumeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUploadUrl",
      "completeUpload",
      "listResumes",
      "getResume",
      "deleteResume",
      "validateResume",
      "getResumeChunks",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ResumeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ResumeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RESUME_SERVICE_NAME = "ResumeService";
