// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: interview/v1/interview.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  InterviewRoundProto,
  InterviewStageProto,
  InterviewStatusProto,
  InterviewTurnStatusProto,
  InterviewTypeProto,
} from "../../common/v1/enums";

export const protobufPackage = "interview.v1";

/** === 메시지 정의 (DTO) === */
export interface CreateInterviewRequest {
  /** UUID */
  userId: string;
  /** UUID (optional - 이력서 없이도 면접 가능) */
  resumeId?: string | undefined;
  companyName: string;
  domain: string;
  type: InterviewTypeProto;
  participatingPersonas: string[];
  scheduledDurationMinutes: number;
  round: InterviewRoundProto;
  jobPostingUrl?: string | undefined;
  selfIntroText?: string | undefined;
}

export interface CreateInterviewResponse {
  /** UUID */
  interviewId: string;
  status: InterviewStatusProto;
}

/** Stage 조회 */
export interface GetInterviewStageRequest {
  interviewId: string;
}

export interface GetInterviewStageResponse {
  stage: InterviewStageProto;
  selfIntroElapsedSeconds: number;
  participatingPersonas: string[];
  domain?: string | undefined;
  selfIntroRetryCount: number;
  turnStatus: InterviewTurnStatusProto;
  turnCount: number;
  activePersonaId?: string | undefined;
  canCandidateSpeak: boolean;
}

/** Stage 전환 */
export interface TransitionStageRequest {
  interviewId: string;
  newStage: InterviewStageProto;
}

export interface TransitionStageResponse {
  currentStage: InterviewStageProto;
}

/** 사용자 답변 직접 처리 */
export interface ProcessUserAnswerRequest {
  interviewId: string;
  userText: string;
  userId: string;
  timestamp: string;
}

export interface ProcessUserAnswerResponse {
  success: boolean;
}

export interface SaveInterviewMessageRequest {
  interviewId: string;
  role: string;
  content: string;
  stage?: string | undefined;
  personaId?: string | undefined;
  turnCount: number;
  sequenceNumber: number;
  difficultyLevel?: number | undefined;
}

export interface SaveInterviewMessageResponse {
  success: boolean;
}

/** 자기소개 리트라이 고속 제어 (STT 우회) */
export interface RetrySelfIntroRequest {
  interviewId: string;
  durationSeconds: number;
}

export interface RetrySelfIntroResponse {
  success: boolean;
  newRetryCount: number;
  isMaxRetryExceeded: boolean;
}

/** 면접 목록 조회 */
export interface ListInterviewsRequest {
  /** UUID */
  userId: string;
  /** 필터링할 상태 목록 (Optional) */
  status: InterviewStatusProto[];
  /** 조회 개수 제한 (Optional, 0이면 전체) */
  limit: number;
  /** 정렬 기준 (예: "desc", "asc" - start_at 기준) */
  sort: string;
}

export interface InterviewSummary {
  interviewId: string;
  /** ISO 8601 */
  startedAt: string;
  status: InterviewStatusProto;
  companyName: string;
  domain: string;
  type: InterviewTypeProto;
  scheduledDurationMinutes: number;
  jobPostingUrl?: string | undefined;
}

export interface ListInterviewsResponse {
  interviews: InterviewSummary[];
}

/** 면접 이력 조회 */
export interface GetInterviewHistoryRequest {
  interviewId: string;
}

export interface GetInterviewHistoryResponse {
  messages: InterviewMessage[];
}

export interface InterviewMessage {
  /** USER, ASSISTANT, SYSTEM */
  role: string;
  /** TEXT, EVENT, STAGE_TRANSITION */
  type: string;
  /** 메시지 내용 */
  content: string;
  /** ISO 8601 형식 */
  timestamp: string;
  /** 추가 메타데이터 */
  payload: { [key: string]: string };
}

export interface InterviewMessage_PayloadEntry {
  key: string;
  value: string;
}

/** 면접 완료 */
export interface CompleteInterviewRequest {
  interviewId: string;
}

export interface CompleteInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  endedAt: string;
}

/** 면접 취소 */
export interface CancelInterviewRequest {
  interviewId: string;
  /** 취소 사유 (선택적) */
  reason: string;
}

export interface CancelInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  endedAt: string;
}

/** 면접 중지 */
export interface PauseInterviewRequest {
  interviewId: string;
}

export interface PauseInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  pausedAt: string;
}

/** 면접 재개 */
export interface ResumeInterviewRequest {
  interviewId: string;
}

export interface ResumeInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  resumedAt: string;
}

/** [DevTool] 면접 단계 강제 변경 */
export interface ForceStageRequest {
  interviewId: string;
  targetStage: InterviewStageProto;
}

export interface ForceStageResponse {
  interviewId: string;
  currentStage: InterviewStageProto;
  message: string;
}

/** 면접 단건 조회 */
export interface GetInterviewRequest {
  interviewId: string;
}

export interface GetInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  currentStage: InterviewStageProto;
  type: InterviewTypeProto;
  companyName: string;
  domain: string;
  scheduledDurationMinutes: number;
  participatingPersonas: string[];
  createdAt?: string | undefined;
  resumedAt?: string | undefined;
  round: InterviewRoundProto;
  jobPostingUrl?: string | undefined;
  selfIntroText?: string | undefined;
  turnCount: number;
}

/** 면접 리포트 생성 */
export interface CreateInterviewReportRequest {
  interviewId: string;
}

export interface CreateInterviewReportResponse {
  reportId: string;
  generationStatus: string;
}

/** 면접 리포트 조회 */
export interface GetInterviewReportRequest {
  interviewId: string;
  reportId: string;
}

export interface GetInterviewReportResponse {
  reportId: string;
  generationStatus: string;
  totalScore: number;
  passFailStatus: string;
  summaryText: string;
  resumeFeedback: string;
}

/** 면접 영상 세그먼트 업로드 URL 발급 */
export interface GetRecordingSegmentUploadUrlRequest {
  interviewId: string;
  turnCount: number;
}

export interface GetRecordingSegmentUploadUrlResponse {
  uploadUrl: string;
  objectKey: string;
}

/** 면접 영상 세그먼트 업로드 완료 신고 */
export interface CompleteRecordingSegmentUploadRequest {
  interviewId: string;
  objectKey: string;
  turnCount: number;
  durationSeconds: number;
  startedAtEpoch: number;
  endedAtEpoch: number;
}

export interface CompleteRecordingSegmentUploadResponse {
  success: boolean;
}

/** 면접 영상 세그먼트 목록 조회 (다시 보기) */
export interface GetInterviewRecordingSegmentsRequest {
  interviewId: string;
}

export interface RecordingSegment {
  turnCount: number;
  /** 지원자 영상 URL */
  recordingUrl: string;
  expiresAtEpoch: number;
  /** 면접관 질문 텍스트 */
  questionContent: string;
  /** 지원자 답변 텍스트 (STT) */
  answerContent: string;
  /** 면접관 질문 음성 URL (TTS) */
  questionAudioUrl: string;
  /** 지원자 답변 음성 URL (STT 원본) */
  answerAudioUrl: string;
}

export interface GetInterviewRecordingSegmentsResponse {
  segments: RecordingSegment[];
}

export const INTERVIEW_V1_PACKAGE_NAME = "interview.v1";

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceClient {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(request: CreateInterviewRequest, metadata?: Metadata): Observable<CreateInterviewResponse>;

  /** Stage 관리 */

  getInterviewStage(request: GetInterviewStageRequest, metadata?: Metadata): Observable<GetInterviewStageResponse>;

  transitionStage(request: TransitionStageRequest, metadata?: Metadata): Observable<TransitionStageResponse>;

  /** 자기소개 리트라이 제어 (STT 우회) */

  retrySelfIntro(request: RetrySelfIntroRequest, metadata?: Metadata): Observable<RetrySelfIntroResponse>;

  /** 면접 목록 조회 */

  listInterviews(request: ListInterviewsRequest, metadata?: Metadata): Observable<ListInterviewsResponse>;

  /** 면접 이력 조회 */

  getInterviewHistory(
    request: GetInterviewHistoryRequest,
    metadata?: Metadata,
  ): Observable<GetInterviewHistoryResponse>;

  /** 면접 완료 (정상 종료) */

  completeInterview(request: CompleteInterviewRequest, metadata?: Metadata): Observable<CompleteInterviewResponse>;

  /** 면접 취소 (비정상 종료) */

  cancelInterview(request: CancelInterviewRequest, metadata?: Metadata): Observable<CancelInterviewResponse>;

  /** 면접 중지 */

  pauseInterview(request: PauseInterviewRequest, metadata?: Metadata): Observable<PauseInterviewResponse>;

  /** 면접 재개 */

  resumeInterview(request: ResumeInterviewRequest, metadata?: Metadata): Observable<ResumeInterviewResponse>;

  /** 사용자 답변 직접 처리 (자기소개 완료/스킵 등 Socket에서 직접 트리거 시) */

  processUserAnswer(request: ProcessUserAnswerRequest, metadata?: Metadata): Observable<ProcessUserAnswerResponse>;

  /** 프론트에서 재생된 시스템 음성/텍스트를 대화 히스토리에 저장 */

  saveInterviewMessage(
    request: SaveInterviewMessageRequest,
    metadata?: Metadata,
  ): Observable<SaveInterviewMessageResponse>;

  /** [DevTool] 면접 단계 강제 변경 (개발 환경 전용) */

  forceStage(request: ForceStageRequest, metadata?: Metadata): Observable<ForceStageResponse>;

  /** 면접 단건 조회 (상태 확인용) */

  getInterview(request: GetInterviewRequest, metadata?: Metadata): Observable<GetInterviewResponse>;

  /** 면접 리포트 생성 */

  createInterviewReport(
    request: CreateInterviewReportRequest,
    metadata?: Metadata,
  ): Observable<CreateInterviewReportResponse>;

  /** 면접 리포트 조회 */

  getInterviewReport(request: GetInterviewReportRequest, metadata?: Metadata): Observable<GetInterviewReportResponse>;

  /** 면접 영상 세그먼트 업로드 URL 발급 */

  getRecordingSegmentUploadUrl(
    request: GetRecordingSegmentUploadUrlRequest,
    metadata?: Metadata,
  ): Observable<GetRecordingSegmentUploadUrlResponse>;

  /** 면접 영상 세그먼트 업로드 완료 신고 */

  completeRecordingSegmentUpload(
    request: CompleteRecordingSegmentUploadRequest,
    metadata?: Metadata,
  ): Observable<CompleteRecordingSegmentUploadResponse>;

  /** 면접 영상 세그먼트 목록 조회 (다시 보기) */

  getInterviewRecordingSegments(
    request: GetInterviewRecordingSegmentsRequest,
    metadata?: Metadata,
  ): Observable<GetInterviewRecordingSegmentsResponse>;
}

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceController {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(
    request: CreateInterviewRequest,
    metadata?: Metadata,
  ): Promise<CreateInterviewResponse> | Observable<CreateInterviewResponse> | CreateInterviewResponse;

  /** Stage 관리 */

  getInterviewStage(
    request: GetInterviewStageRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewStageResponse> | Observable<GetInterviewStageResponse> | GetInterviewStageResponse;

  transitionStage(
    request: TransitionStageRequest,
    metadata?: Metadata,
  ): Promise<TransitionStageResponse> | Observable<TransitionStageResponse> | TransitionStageResponse;

  /** 자기소개 리트라이 제어 (STT 우회) */

  retrySelfIntro(
    request: RetrySelfIntroRequest,
    metadata?: Metadata,
  ): Promise<RetrySelfIntroResponse> | Observable<RetrySelfIntroResponse> | RetrySelfIntroResponse;

  /** 면접 목록 조회 */

  listInterviews(
    request: ListInterviewsRequest,
    metadata?: Metadata,
  ): Promise<ListInterviewsResponse> | Observable<ListInterviewsResponse> | ListInterviewsResponse;

  /** 면접 이력 조회 */

  getInterviewHistory(
    request: GetInterviewHistoryRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewHistoryResponse> | Observable<GetInterviewHistoryResponse> | GetInterviewHistoryResponse;

  /** 면접 완료 (정상 종료) */

  completeInterview(
    request: CompleteInterviewRequest,
    metadata?: Metadata,
  ): Promise<CompleteInterviewResponse> | Observable<CompleteInterviewResponse> | CompleteInterviewResponse;

  /** 면접 취소 (비정상 종료) */

  cancelInterview(
    request: CancelInterviewRequest,
    metadata?: Metadata,
  ): Promise<CancelInterviewResponse> | Observable<CancelInterviewResponse> | CancelInterviewResponse;

  /** 면접 중지 */

  pauseInterview(
    request: PauseInterviewRequest,
    metadata?: Metadata,
  ): Promise<PauseInterviewResponse> | Observable<PauseInterviewResponse> | PauseInterviewResponse;

  /** 면접 재개 */

  resumeInterview(
    request: ResumeInterviewRequest,
    metadata?: Metadata,
  ): Promise<ResumeInterviewResponse> | Observable<ResumeInterviewResponse> | ResumeInterviewResponse;

  /** 사용자 답변 직접 처리 (자기소개 완료/스킵 등 Socket에서 직접 트리거 시) */

  processUserAnswer(
    request: ProcessUserAnswerRequest,
    metadata?: Metadata,
  ): Promise<ProcessUserAnswerResponse> | Observable<ProcessUserAnswerResponse> | ProcessUserAnswerResponse;

  /** 프론트에서 재생된 시스템 음성/텍스트를 대화 히스토리에 저장 */

  saveInterviewMessage(
    request: SaveInterviewMessageRequest,
    metadata?: Metadata,
  ): Promise<SaveInterviewMessageResponse> | Observable<SaveInterviewMessageResponse> | SaveInterviewMessageResponse;

  /** [DevTool] 면접 단계 강제 변경 (개발 환경 전용) */

  forceStage(
    request: ForceStageRequest,
    metadata?: Metadata,
  ): Promise<ForceStageResponse> | Observable<ForceStageResponse> | ForceStageResponse;

  /** 면접 단건 조회 (상태 확인용) */

  getInterview(
    request: GetInterviewRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewResponse> | Observable<GetInterviewResponse> | GetInterviewResponse;

  /** 면접 리포트 생성 */

  createInterviewReport(
    request: CreateInterviewReportRequest,
    metadata?: Metadata,
  ): Promise<CreateInterviewReportResponse> | Observable<CreateInterviewReportResponse> | CreateInterviewReportResponse;

  /** 면접 리포트 조회 */

  getInterviewReport(
    request: GetInterviewReportRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewReportResponse> | Observable<GetInterviewReportResponse> | GetInterviewReportResponse;

  /** 면접 영상 세그먼트 업로드 URL 발급 */

  getRecordingSegmentUploadUrl(
    request: GetRecordingSegmentUploadUrlRequest,
    metadata?: Metadata,
  ):
    | Promise<GetRecordingSegmentUploadUrlResponse>
    | Observable<GetRecordingSegmentUploadUrlResponse>
    | GetRecordingSegmentUploadUrlResponse;

  /** 면접 영상 세그먼트 업로드 완료 신고 */

  completeRecordingSegmentUpload(
    request: CompleteRecordingSegmentUploadRequest,
    metadata?: Metadata,
  ):
    | Promise<CompleteRecordingSegmentUploadResponse>
    | Observable<CompleteRecordingSegmentUploadResponse>
    | CompleteRecordingSegmentUploadResponse;

  /** 면접 영상 세그먼트 목록 조회 (다시 보기) */

  getInterviewRecordingSegments(
    request: GetInterviewRecordingSegmentsRequest,
    metadata?: Metadata,
  ):
    | Promise<GetInterviewRecordingSegmentsResponse>
    | Observable<GetInterviewRecordingSegmentsResponse>
    | GetInterviewRecordingSegmentsResponse;
}

export function InterviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createInterview",
      "getInterviewStage",
      "transitionStage",
      "retrySelfIntro",
      "listInterviews",
      "getInterviewHistory",
      "completeInterview",
      "cancelInterview",
      "pauseInterview",
      "resumeInterview",
      "processUserAnswer",
      "saveInterviewMessage",
      "forceStage",
      "getInterview",
      "createInterviewReport",
      "getInterviewReport",
      "getRecordingSegmentUploadUrl",
      "completeRecordingSegmentUpload",
      "getInterviewRecordingSegments",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERVIEW_SERVICE_NAME = "InterviewService";
