// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: interview/v1/interview.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import {
  InterviewPersonalityProto,
  InterviewRoleProto,
  InterviewStageProto,
  InterviewStatusProto,
  InterviewTypeProto,
} from "../../common/v1/enums";

export const protobufPackage = "interview.v1";

/** === 메시지 정의 (DTO) === */
export interface CreateInterviewRequest {
  /** UUID */
  userId: string;
  /** UUID (optional - 이력서 없이도 면접 가능) */
  resumeId?: string | undefined;
  domain: string;
  type: InterviewTypeProto;
  /** 복수 선택 가능 (New) */
  interviewerRoles: InterviewRoleProto[];
  /** 면접 분위기 (New) */
  personality: InterviewPersonalityProto;
  targetDurationMinutes: number;
  selfIntroduction: string;
  interviewerCount: number;
}

export interface CreateInterviewResponse {
  /** UUID */
  interviewId: string;
  status: InterviewStatusProto;
}

/** Stage 조회 */
export interface GetInterviewStageRequest {
  interviewId: string;
}

export interface GetInterviewStageResponse {
  stage: InterviewStageProto;
  selfIntroElapsedSeconds: number;
  persona?: string | undefined;
  interviewerCount?: number | undefined;
  domain?: string | undefined;
  selfIntroRetryCount: number;
  interviewerRoles: InterviewRoleProto[];
  personality: InterviewPersonalityProto;
}

/** Stage 전환 */
export interface TransitionStageRequest {
  interviewId: string;
  newStage: InterviewStageProto;
}

export interface TransitionStageResponse {
  currentStage: InterviewStageProto;
}

/** 자기소개 재시도 증분 */
export interface IncrementSelfIntroRetryRequest {
  interviewId: string;
}

export interface IncrementSelfIntroRetryResponse {
  newRetryCount: number;
}

/** 면접 목록 조회 */
export interface ListInterviewsRequest {
  /** UUID */
  userId: string;
  /** 필터링할 상태 목록 (Optional) */
  status: InterviewStatusProto[];
  /** 조회 개수 제한 (Optional, 0이면 전체) */
  limit: number;
  /** 정렬 기준 (예: "desc", "asc" - start_at 기준) */
  sort: string;
}

export interface InterviewSummary {
  interviewId: string;
  /** ISO 8601 */
  startedAt: string;
  status: InterviewStatusProto;
  domain: string;
  type: InterviewTypeProto;
  targetDurationMinutes: number;
  interviewerCount: number;
}

export interface ListInterviewsResponse {
  interviews: InterviewSummary[];
}

/** 면접 이력 조회 */
export interface GetInterviewHistoryRequest {
  interviewId: string;
}

export interface GetInterviewHistoryResponse {
  messages: InterviewMessage[];
}

export interface InterviewMessage {
  /** USER, ASSISTANT, SYSTEM */
  role: string;
  /** TEXT, EVENT, STAGE_TRANSITION */
  type: string;
  /** 메시지 내용 */
  content: string;
  /** ISO 8601 형식 */
  timestamp: string;
  /** 추가 메타데이터 */
  payload: { [key: string]: string };
}

export interface InterviewMessage_PayloadEntry {
  key: string;
  value: string;
}

/** 면접 완료 */
export interface CompleteInterviewRequest {
  interviewId: string;
}

export interface CompleteInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  endedAt: string;
}

/** 면접 취소 */
export interface CancelInterviewRequest {
  interviewId: string;
  /** 취소 사유 (선택적) */
  reason: string;
}

export interface CancelInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  endedAt: string;
}

/** 면접 중지 */
export interface PauseInterviewRequest {
  interviewId: string;
}

export interface PauseInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  pausedAt: string;
}

/** 면접 재개 */
export interface ResumeInterviewRequest {
  interviewId: string;
}

export interface ResumeInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  /** ISO 8601 */
  resumedAt: string;
}

/** [DevTool] 면접 단계 강제 변경 */
export interface ForceStageRequest {
  interviewId: string;
  targetStage: InterviewStageProto;
}

export interface ForceStageResponse {
  interviewId: string;
  currentStage: InterviewStageProto;
  message: string;
}

/** 면접 단건 조회 */
export interface GetInterviewRequest {
  interviewId: string;
}

export interface GetInterviewResponse {
  interviewId: string;
  status: InterviewStatusProto;
  currentStage: InterviewStageProto;
  type: InterviewTypeProto;
  domain: string;
  targetDurationMinutes: number;
  selfIntroduction: string;
  interviewerRoles: InterviewRoleProto[];
  personality: InterviewPersonalityProto;
  interviewerCount: number;
  createdAt?: string | undefined;
  resumedAt?: string | undefined;
}

export const INTERVIEW_V1_PACKAGE_NAME = "interview.v1";

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceClient {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(request: CreateInterviewRequest, metadata?: Metadata): Observable<CreateInterviewResponse>;

  /** Stage 관리 */

  getInterviewStage(request: GetInterviewStageRequest, metadata?: Metadata): Observable<GetInterviewStageResponse>;

  transitionStage(request: TransitionStageRequest, metadata?: Metadata): Observable<TransitionStageResponse>;

  /** 자기소개 재시도 제어 */

  incrementSelfIntroRetry(
    request: IncrementSelfIntroRetryRequest,
    metadata?: Metadata,
  ): Observable<IncrementSelfIntroRetryResponse>;

  /** 면접 목록 조회 */

  listInterviews(request: ListInterviewsRequest, metadata?: Metadata): Observable<ListInterviewsResponse>;

  /** 면접 이력 조회 */

  getInterviewHistory(
    request: GetInterviewHistoryRequest,
    metadata?: Metadata,
  ): Observable<GetInterviewHistoryResponse>;

  /** 면접 완료 (정상 종료) */

  completeInterview(request: CompleteInterviewRequest, metadata?: Metadata): Observable<CompleteInterviewResponse>;

  /** 면접 취소 (비정상 종료) */

  cancelInterview(request: CancelInterviewRequest, metadata?: Metadata): Observable<CancelInterviewResponse>;

  /** 면접 중지 */

  pauseInterview(request: PauseInterviewRequest, metadata?: Metadata): Observable<PauseInterviewResponse>;

  /** 면접 재개 */

  resumeInterview(request: ResumeInterviewRequest, metadata?: Metadata): Observable<ResumeInterviewResponse>;

  /** [DevTool] 면접 단계 강제 변경 (개발 환경 전용) */

  forceStage(request: ForceStageRequest, metadata?: Metadata): Observable<ForceStageResponse>;

  /** 면접 단건 조회 (상태 확인용) */

  getInterview(request: GetInterviewRequest, metadata?: Metadata): Observable<GetInterviewResponse>;
}

/** === 서비스 정의 (인터페이스) === */

export interface InterviewServiceController {
  /** 면접 세션 생성 요청을 받아서 응답을 반환한다. */

  createInterview(
    request: CreateInterviewRequest,
    metadata?: Metadata,
  ): Promise<CreateInterviewResponse> | Observable<CreateInterviewResponse> | CreateInterviewResponse;

  /** Stage 관리 */

  getInterviewStage(
    request: GetInterviewStageRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewStageResponse> | Observable<GetInterviewStageResponse> | GetInterviewStageResponse;

  transitionStage(
    request: TransitionStageRequest,
    metadata?: Metadata,
  ): Promise<TransitionStageResponse> | Observable<TransitionStageResponse> | TransitionStageResponse;

  /** 자기소개 재시도 제어 */

  incrementSelfIntroRetry(
    request: IncrementSelfIntroRetryRequest,
    metadata?: Metadata,
  ):
    | Promise<IncrementSelfIntroRetryResponse>
    | Observable<IncrementSelfIntroRetryResponse>
    | IncrementSelfIntroRetryResponse;

  /** 면접 목록 조회 */

  listInterviews(
    request: ListInterviewsRequest,
    metadata?: Metadata,
  ): Promise<ListInterviewsResponse> | Observable<ListInterviewsResponse> | ListInterviewsResponse;

  /** 면접 이력 조회 */

  getInterviewHistory(
    request: GetInterviewHistoryRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewHistoryResponse> | Observable<GetInterviewHistoryResponse> | GetInterviewHistoryResponse;

  /** 면접 완료 (정상 종료) */

  completeInterview(
    request: CompleteInterviewRequest,
    metadata?: Metadata,
  ): Promise<CompleteInterviewResponse> | Observable<CompleteInterviewResponse> | CompleteInterviewResponse;

  /** 면접 취소 (비정상 종료) */

  cancelInterview(
    request: CancelInterviewRequest,
    metadata?: Metadata,
  ): Promise<CancelInterviewResponse> | Observable<CancelInterviewResponse> | CancelInterviewResponse;

  /** 면접 중지 */

  pauseInterview(
    request: PauseInterviewRequest,
    metadata?: Metadata,
  ): Promise<PauseInterviewResponse> | Observable<PauseInterviewResponse> | PauseInterviewResponse;

  /** 면접 재개 */

  resumeInterview(
    request: ResumeInterviewRequest,
    metadata?: Metadata,
  ): Promise<ResumeInterviewResponse> | Observable<ResumeInterviewResponse> | ResumeInterviewResponse;

  /** [DevTool] 면접 단계 강제 변경 (개발 환경 전용) */

  forceStage(
    request: ForceStageRequest,
    metadata?: Metadata,
  ): Promise<ForceStageResponse> | Observable<ForceStageResponse> | ForceStageResponse;

  /** 면접 단건 조회 (상태 확인용) */

  getInterview(
    request: GetInterviewRequest,
    metadata?: Metadata,
  ): Promise<GetInterviewResponse> | Observable<GetInterviewResponse> | GetInterviewResponse;
}

export function InterviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createInterview",
      "getInterviewStage",
      "transitionStage",
      "incrementSelfIntroRetry",
      "listInterviews",
      "getInterviewHistory",
      "completeInterview",
      "cancelInterview",
      "pauseInterview",
      "resumeInterview",
      "forceStage",
      "getInterview",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InterviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERVIEW_SERVICE_NAME = "InterviewService";
