apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app
  namespace: argocd
spec:
  description: Application services (auth, bff, interview, document, etc.)
  sourceRepos:
    - '*'
  destinations:
    - namespace: unbrdn
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
