apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: unbrdn
spec:
  type: ExternalName
  externalName: unbrdn-postgres.postgres.database.azure.com
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
