# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from document.v1 import document_pb2 as document_dot_v1_dot_document__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in document/v1/document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Document 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbedding = channel.unary_unary(
                '/document.v1.DocumentService/GenerateEmbedding',
                request_serializer=document_dot_v1_dot_document__pb2.GenerateEmbeddingRequest.SerializeToString,
                response_deserializer=document_dot_v1_dot_document__pb2.GenerateEmbeddingResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Document 서비스
    """

    def GenerateEmbedding(self, request, context):
        """텍스트를 임베딩 벡터로 변환
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=document_dot_v1_dot_document__pb2.GenerateEmbeddingRequest.FromString,
                    response_serializer=document_dot_v1_dot_document__pb2.GenerateEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.v1.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.v1.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Document 서비스
    """

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.v1.DocumentService/GenerateEmbedding',
            document_dot_v1_dot_document__pb2.GenerateEmbeddingRequest.SerializeToString,
            document_dot_v1_dot_document__pb2.GenerateEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
