apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: unbrdn
  labels:
    app: bff
    environment: prod
spec:
  replicas: 2 # HA 구성: SPOF 제거
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
        environment: prod
    spec:
      # 고가용성(HA): BFF를 최대한 넓게 분산 배치
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway # 자리가 없으면 겹쳐서라도 배치 (유연성)
          labelSelector:
            matchLabels:
              app: bff
      # Preemptible 노드 회피 (안정성 확보)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: bff
                topologyKey: kubernetes.io/hostname

      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: bff
          image: unbrdnacr.azurecr.io/bff:728b871c186566f40b66c2824038593519fe6cf9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: bff-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: bff-static
              mountPath: /app/static
              readOnly: true
      volumes:
        - name: bff-static
          configMap:
            name: bff-static
            optional: true
      restartPolicy: Always
