apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storage-secrets
  namespace: unbrdn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: storage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AZURE_STORAGE_CONNECTION_STRING
      remoteRef:
        key: storage-connection-string
    - secretKey: MONGODB_URI
      remoteRef:
        key: mongo-uri
