apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: unbrdn
  labels:
    app: storage
spec:
  selector:
    app: storage
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
