// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: document/v1/document.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "document.v1";

/** 임베딩 생성 요청 */
export interface GenerateEmbeddingRequest {
  /** 임베딩할 텍스트 */
  text: string;
}

/** 임베딩 생성 응답 */
export interface GenerateEmbeddingResponse {
  /** 임베딩 벡터 (384차원) */
  embedding: number[];
  /** 벡터 차원 수 */
  dimension: number;
}

export const DOCUMENT_V1_PACKAGE_NAME = "document.v1";

/** Document 서비스 */

export interface DocumentServiceClient {
  /** 텍스트를 임베딩 벡터로 변환 */

  generateEmbedding(request: GenerateEmbeddingRequest, metadata?: Metadata): Observable<GenerateEmbeddingResponse>;
}

/** Document 서비스 */

export interface DocumentServiceController {
  /** 텍스트를 임베딩 벡터로 변환 */

  generateEmbedding(
    request: GenerateEmbeddingRequest,
    metadata?: Metadata,
  ): Promise<GenerateEmbeddingResponse> | Observable<GenerateEmbeddingResponse> | GenerateEmbeddingResponse;
}

export function DocumentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generateEmbedding"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DocumentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DocumentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DOCUMENT_SERVICE_NAME = "DocumentService";
