// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: stt/v1/stt.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "stt.v1";

/** 면접 컨텍스트 */
export interface InterviewContext {
  interviewId: string;
  userId: string;
  /** "SELF_INTRO", "IN_PROGRESS", "LAST_ANSWER", etc. */
  stage: string;
}

/** 일반 STT 컨텍스트 (향후 확장용) */
export interface GeneralContext {
  sessionId: string;
  appName: string;
}

/** 오디오 컨텍스트 (비즈니스 메타데이터) */
export interface AudioContext {
  /** 추적 ID */
  traceId: string;
  /** "practice" (로컬 Whisper) or "real" (OpenAI API) */
  mode: string;
  interview?: InterviewContext | undefined;
  general?: GeneralContext | undefined;
}

/** 오디오 청크 (순수 오디오 데이터 + 컨텍스트) */
export interface AudioChunk {
  /** 오디오 데이터 */
  audioData: Uint8Array;
  /** 마지막 청크 여부 */
  isFinal: boolean;
  /** "pcm16" or "webm" */
  audioFormat: string;
  /** 샘플 레이트 (기본 16000) */
  sampleRate: number;
  /** 입력 게인 (기본 1.0) */
  inputGain: number;
  /** 임계값 (기본 5.0) */
  threshold: number;
  /** ISO 8601 타임스탬프 */
  timestamp: string;
  /** 비즈니스 컨텍스트 */
  context: AudioContext | undefined;
}

export interface STTResponse {
  /** 변환된 텍스트 */
  text: string;
  /** 인터뷰 ID (UUID) */
  interviewId: string;
  /** 사용자 ID */
  userId: string;
  /** 빈 응답 여부 */
  isEmpty: boolean;
  /** "faster-whisper" */
  engine: string;
  /** 추적 ID */
  traceId: string;
  /** ISO 8601 타임스탬프 */
  timestamp: string;
}

export const STT_V1_PACKAGE_NAME = "stt.v1";

export interface SttServiceClient {
  /** STT (Speech-to-Text) 서비스 - 스트리밍 */

  speechToText(request: Observable<AudioChunk>, metadata?: Metadata): Observable<STTResponse>;
}

export interface SttServiceController {
  /** STT (Speech-to-Text) 서비스 - 스트리밍 */

  speechToText(
    request: Observable<AudioChunk>,
    metadata?: Metadata,
  ): Promise<STTResponse> | Observable<STTResponse> | STTResponse;
}

export function SttServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SttService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["speechToText"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SttService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STT_SERVICE_NAME = "SttService";
