// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.4
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface FindUserByEmailRequest {
  email: string;
}

export interface FindUserByEmailResponse {
  candidate?: Candidate | undefined;
  recruiter?: Recruiter | undefined;
}

export interface FindUserByIdRequest {
  /** UUID */
  userId: string;
}

export interface FindUserByIdResponse {
  candidate?: Candidate | undefined;
  recruiter?: Recruiter | undefined;
}

export interface Candidate {
  /** UUID */
  id: string;
  email: string;
  nickname: string;
  role: string;
  phoneNumber: string;
  verifiedEmail: string;
  passwordHash: string;
}

export interface Recruiter {
  /** UUID */
  id: string;
  email: string;
  nickname: string;
  role: string;
  phoneNumber: string;
  verifiedEmail: string;
  companyCode: string;
  passwordHash: string;
}

export interface RegisterCandidateRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
}

export interface RegisterRecruiterRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
  companyCode: string;
}

export interface RegisterUserResponse {
  userId: string;
}

export const USER_PACKAGE_NAME = "user";

function createBaseFindUserByEmailRequest(): FindUserByEmailRequest {
  return { email: "" };
}

export const FindUserByEmailRequest: MessageFns<FindUserByEmailRequest> = {
  encode(message: FindUserByEmailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByEmailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByEmailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFindUserByEmailResponse(): FindUserByEmailResponse {
  return {};
}

export const FindUserByEmailResponse: MessageFns<FindUserByEmailResponse> = {
  encode(message: FindUserByEmailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== undefined) {
      Candidate.encode(message.candidate, writer.uint32(10).fork()).join();
    }
    if (message.recruiter !== undefined) {
      Recruiter.encode(message.recruiter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByEmailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByEmailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = Candidate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.recruiter = Recruiter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFindUserByIdRequest(): FindUserByIdRequest {
  return { userId: "" };
}

export const FindUserByIdRequest: MessageFns<FindUserByIdRequest> = {
  encode(message: FindUserByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFindUserByIdResponse(): FindUserByIdResponse {
  return {};
}

export const FindUserByIdResponse: MessageFns<FindUserByIdResponse> = {
  encode(message: FindUserByIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== undefined) {
      Candidate.encode(message.candidate, writer.uint32(10).fork()).join();
    }
    if (message.recruiter !== undefined) {
      Recruiter.encode(message.recruiter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindUserByIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindUserByIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = Candidate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.recruiter = Recruiter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCandidate(): Candidate {
  return { id: "", email: "", nickname: "", role: "", phoneNumber: "", verifiedEmail: "", passwordHash: "" };
}

export const Candidate: MessageFns<Candidate> = {
  encode(message: Candidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.role !== "") {
      writer.uint32(34).string(message.role);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(42).string(message.phoneNumber);
    }
    if (message.verifiedEmail !== "") {
      writer.uint32(50).string(message.verifiedEmail);
    }
    if (message.passwordHash !== "") {
      writer.uint32(58).string(message.passwordHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Candidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.verifiedEmail = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRecruiter(): Recruiter {
  return {
    id: "",
    email: "",
    nickname: "",
    role: "",
    phoneNumber: "",
    verifiedEmail: "",
    companyCode: "",
    passwordHash: "",
  };
}

export const Recruiter: MessageFns<Recruiter> = {
  encode(message: Recruiter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.role !== "") {
      writer.uint32(34).string(message.role);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(42).string(message.phoneNumber);
    }
    if (message.verifiedEmail !== "") {
      writer.uint32(50).string(message.verifiedEmail);
    }
    if (message.companyCode !== "") {
      writer.uint32(58).string(message.companyCode);
    }
    if (message.passwordHash !== "") {
      writer.uint32(66).string(message.passwordHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Recruiter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecruiter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.verifiedEmail = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.companyCode = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRegisterCandidateRequest(): RegisterCandidateRequest {
  return { email: "", password: "", nickname: "", phoneNumber: "" };
}

export const RegisterCandidateRequest: MessageFns<RegisterCandidateRequest> = {
  encode(message: RegisterCandidateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(34).string(message.phoneNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterCandidateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterCandidateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRegisterRecruiterRequest(): RegisterRecruiterRequest {
  return { email: "", password: "", nickname: "", phoneNumber: "", companyCode: "" };
}

export const RegisterRecruiterRequest: MessageFns<RegisterRecruiterRequest> = {
  encode(message: RegisterRecruiterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.nickname !== "") {
      writer.uint32(26).string(message.nickname);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(34).string(message.phoneNumber);
    }
    if (message.companyCode !== "") {
      writer.uint32(42).string(message.companyCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterRecruiterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterRecruiterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.companyCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRegisterUserResponse(): RegisterUserResponse {
  return { userId: "" };
}

export const RegisterUserResponse: MessageFns<RegisterUserResponse> = {
  encode(message: RegisterUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface UserServiceClient {
  findUserByEmail(request: FindUserByEmailRequest): Observable<FindUserByEmailResponse>;

  findUserById(request: FindUserByIdRequest): Observable<FindUserByIdResponse>;

  registerCandidate(request: RegisterCandidateRequest): Observable<RegisterUserResponse>;

  registerRecruiter(request: RegisterRecruiterRequest): Observable<RegisterUserResponse>;
}

export interface UserServiceController {
  findUserByEmail(
    request: FindUserByEmailRequest,
  ): Promise<FindUserByEmailResponse> | Observable<FindUserByEmailResponse> | FindUserByEmailResponse;

  findUserById(
    request: FindUserByIdRequest,
  ): Promise<FindUserByIdResponse> | Observable<FindUserByIdResponse> | FindUserByIdResponse;

  registerCandidate(
    request: RegisterCandidateRequest,
  ): Promise<RegisterUserResponse> | Observable<RegisterUserResponse> | RegisterUserResponse;

  registerRecruiter(
    request: RegisterRecruiterRequest,
  ): Promise<RegisterUserResponse> | Observable<RegisterUserResponse> | RegisterUserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findUserByEmail", "findUserById", "registerCandidate", "registerRecruiter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  findUserByEmail: {
    path: "/user.UserService/FindUserByEmail",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FindUserByEmailRequest): Buffer =>
      Buffer.from(FindUserByEmailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FindUserByEmailRequest => FindUserByEmailRequest.decode(value),
    responseSerialize: (value: FindUserByEmailResponse): Buffer =>
      Buffer.from(FindUserByEmailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FindUserByEmailResponse => FindUserByEmailResponse.decode(value),
  },
  findUserById: {
    path: "/user.UserService/FindUserById",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FindUserByIdRequest): Buffer => Buffer.from(FindUserByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FindUserByIdRequest => FindUserByIdRequest.decode(value),
    responseSerialize: (value: FindUserByIdResponse): Buffer =>
      Buffer.from(FindUserByIdResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FindUserByIdResponse => FindUserByIdResponse.decode(value),
  },
  registerCandidate: {
    path: "/user.UserService/RegisterCandidate",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RegisterCandidateRequest): Buffer =>
      Buffer.from(RegisterCandidateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterCandidateRequest => RegisterCandidateRequest.decode(value),
    responseSerialize: (value: RegisterUserResponse): Buffer =>
      Buffer.from(RegisterUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegisterUserResponse => RegisterUserResponse.decode(value),
  },
  registerRecruiter: {
    path: "/user.UserService/RegisterRecruiter",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RegisterRecruiterRequest): Buffer =>
      Buffer.from(RegisterRecruiterRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterRecruiterRequest => RegisterRecruiterRequest.decode(value),
    responseSerialize: (value: RegisterUserResponse): Buffer =>
      Buffer.from(RegisterUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegisterUserResponse => RegisterUserResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  findUserByEmail: handleUnaryCall<FindUserByEmailRequest, FindUserByEmailResponse>;
  findUserById: handleUnaryCall<FindUserByIdRequest, FindUserByIdResponse>;
  registerCandidate: handleUnaryCall<RegisterCandidateRequest, RegisterUserResponse>;
  registerRecruiter: handleUnaryCall<RegisterRecruiterRequest, RegisterUserResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
