// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.4
// source: inference.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleServerStreamingCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "inference";

export interface TTSRequest {
  text: string;
  /** "practice" or "real" */
  mode: string;
  /** "PRESSURE", "COMFORTABLE", "RANDOM" */
  persona: string;
  /** 재생 속도 (기본 1.0) */
  speed: number;
}

export interface TTSChunk {
  /** MP3 오디오 청크 */
  audioData: Uint8Array;
  /** 마지막 청크 여부 */
  isFinal: boolean;
}

export const INFERENCE_PACKAGE_NAME = "inference";

function createBaseTTSRequest(): TTSRequest {
  return { text: "", mode: "", persona: "", speed: 0 };
}

export const TTSRequest: MessageFns<TTSRequest> = {
  encode(message: TTSRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.mode !== "") {
      writer.uint32(18).string(message.mode);
    }
    if (message.persona !== "") {
      writer.uint32(26).string(message.persona);
    }
    if (message.speed !== 0) {
      writer.uint32(33).double(message.speed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TTSRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTTSRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.persona = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.speed = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTTSChunk(): TTSChunk {
  return { audioData: new Uint8Array(0), isFinal: false };
}

export const TTSChunk: MessageFns<TTSChunk> = {
  encode(message: TTSChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audioData.length !== 0) {
      writer.uint32(10).bytes(message.audioData);
    }
    if (message.isFinal !== false) {
      writer.uint32(16).bool(message.isFinal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TTSChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTTSChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audioData = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface InferenceServiceClient {
  /** TTS (Text-to-Speech) 서비스 */

  textToSpeech(request: TTSRequest): Observable<TTSChunk>;
}

export interface InferenceServiceController {
  /** TTS (Text-to-Speech) 서비스 */

  textToSpeech(request: TTSRequest): Observable<TTSChunk>;
}

export function InferenceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["textToSpeech"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InferenceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InferenceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INFERENCE_SERVICE_NAME = "InferenceService";

export type InferenceServiceService = typeof InferenceServiceService;
export const InferenceServiceService = {
  /** TTS (Text-to-Speech) 서비스 */
  textToSpeech: {
    path: "/inference.InferenceService/TextToSpeech",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: TTSRequest): Buffer => Buffer.from(TTSRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TTSRequest => TTSRequest.decode(value),
    responseSerialize: (value: TTSChunk): Buffer => Buffer.from(TTSChunk.encode(value).finish()),
    responseDeserialize: (value: Buffer): TTSChunk => TTSChunk.decode(value),
  },
} as const;

export interface InferenceServiceServer extends UntypedServiceImplementation {
  /** TTS (Text-to-Speech) 서비스 */
  textToSpeech: handleServerStreamingCall<TTSRequest, TTSChunk>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
