// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.4
// source: resume.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "resume";

export interface ValidateResumeRequest {
  text: string;
}

export interface ValidateResumeResponse {
  isResume: boolean;
  /** 판별 이유 */
  reason: string;
  /** 매칭 점수 */
  score: number;
}

export interface GetResumeEmbeddingsRequest {
  userId: string;
}

export interface ResumeEmbedding {
  resumeId: string;
  vector: number[];
}

export interface GetResumeEmbeddingsResponse {
  embeddings: ResumeEmbedding[];
}

export interface DeleteResumeRequest {
  resumeId: string;
  userId: string;
}

export interface DeleteResumeResponse {
  success: boolean;
}

export interface GetUploadUrlRequest {
  userId: string;
  fileName: string;
  title: string;
}

export interface GetUploadUrlResponse {
  uploadUrl: string;
  resumeId: string;
}

export interface CompleteUploadRequest {
  resumeId: string;
  /** 프론트엔드에서 전처리가 완료된 검증용 텍스트 */
  validationText: string;
  /** 프론트엔드에서 생성된 검증용 임베딩 벡터 */
  embedding: number[];
  /** 업데이트 시 대체할 기존 이력서 ID */
  existingResumeId?: string | undefined;
}

export interface CompleteUploadResponse {
  success: boolean;
}

export interface ListResumesRequest {
  userId: string;
}

export interface ListResumesResponse {
  resumes: ResumeItem[];
}

export interface ResumeItem {
  id: string;
  title: string;
  status: string;
  createdAt: string;
}

export interface GetResumeRequest {
  resumeId: string;
  userId: string;
}

export interface GetResumeResponse {
  resume: ResumeDetail | undefined;
}

export interface ResumeDetail {
  id: string;
  title: string;
  content: string;
  status: string;
  createdAt: string;
  fileUrl: string;
}

export const RESUME_PACKAGE_NAME = "resume";

function createBaseValidateResumeRequest(): ValidateResumeRequest {
  return { text: "" };
}

export const ValidateResumeRequest: MessageFns<ValidateResumeRequest> = {
  encode(message: ValidateResumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateResumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateResumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateResumeResponse(): ValidateResumeResponse {
  return { isResume: false, reason: "", score: 0 };
}

export const ValidateResumeResponse: MessageFns<ValidateResumeResponse> = {
  encode(message: ValidateResumeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isResume !== false) {
      writer.uint32(8).bool(message.isResume);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.score !== 0) {
      writer.uint32(29).float(message.score);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateResumeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateResumeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isResume = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.score = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetResumeEmbeddingsRequest(): GetResumeEmbeddingsRequest {
  return { userId: "" };
}

export const GetResumeEmbeddingsRequest: MessageFns<GetResumeEmbeddingsRequest> = {
  encode(message: GetResumeEmbeddingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResumeEmbeddingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResumeEmbeddingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseResumeEmbedding(): ResumeEmbedding {
  return { resumeId: "", vector: [] };
}

export const ResumeEmbedding: MessageFns<ResumeEmbedding> = {
  encode(message: ResumeEmbedding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resumeId !== "") {
      writer.uint32(10).string(message.resumeId);
    }
    writer.uint32(18).fork();
    for (const v of message.vector) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResumeEmbedding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResumeEmbedding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
        case 2: {
          if (tag === 21) {
            message.vector.push(reader.float());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.vector.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetResumeEmbeddingsResponse(): GetResumeEmbeddingsResponse {
  return { embeddings: [] };
}

export const GetResumeEmbeddingsResponse: MessageFns<GetResumeEmbeddingsResponse> = {
  encode(message: GetResumeEmbeddingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.embeddings) {
      ResumeEmbedding.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResumeEmbeddingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResumeEmbeddingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.embeddings.push(ResumeEmbedding.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteResumeRequest(): DeleteResumeRequest {
  return { resumeId: "", userId: "" };
}

export const DeleteResumeRequest: MessageFns<DeleteResumeRequest> = {
  encode(message: DeleteResumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resumeId !== "") {
      writer.uint32(10).string(message.resumeId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteResumeResponse(): DeleteResumeResponse {
  return { success: false };
}

export const DeleteResumeResponse: MessageFns<DeleteResumeResponse> = {
  encode(message: DeleteResumeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResumeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResumeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUploadUrlRequest(): GetUploadUrlRequest {
  return { userId: "", fileName: "", title: "" };
}

export const GetUploadUrlRequest: MessageFns<GetUploadUrlRequest> = {
  encode(message: GetUploadUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadUrlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUploadUrlResponse(): GetUploadUrlResponse {
  return { uploadUrl: "", resumeId: "" };
}

export const GetUploadUrlResponse: MessageFns<GetUploadUrlResponse> = {
  encode(message: GetUploadUrlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadUrl !== "") {
      writer.uint32(10).string(message.uploadUrl);
    }
    if (message.resumeId !== "") {
      writer.uint32(18).string(message.resumeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadUrlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCompleteUploadRequest(): CompleteUploadRequest {
  return { resumeId: "", validationText: "", embedding: [] };
}

export const CompleteUploadRequest: MessageFns<CompleteUploadRequest> = {
  encode(message: CompleteUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resumeId !== "") {
      writer.uint32(10).string(message.resumeId);
    }
    if (message.validationText !== "") {
      writer.uint32(18).string(message.validationText);
    }
    writer.uint32(26).fork();
    for (const v of message.embedding) {
      writer.float(v);
    }
    writer.join();
    if (message.existingResumeId !== undefined) {
      writer.uint32(34).string(message.existingResumeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.validationText = reader.string();
          continue;
        }
        case 3: {
          if (tag === 29) {
            message.embedding.push(reader.float());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.embedding.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.existingResumeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCompleteUploadResponse(): CompleteUploadResponse {
  return { success: false };
}

export const CompleteUploadResponse: MessageFns<CompleteUploadResponse> = {
  encode(message: CompleteUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListResumesRequest(): ListResumesRequest {
  return { userId: "" };
}

export const ListResumesRequest: MessageFns<ListResumesRequest> = {
  encode(message: ListResumesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResumesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResumesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListResumesResponse(): ListResumesResponse {
  return { resumes: [] };
}

export const ListResumesResponse: MessageFns<ListResumesResponse> = {
  encode(message: ListResumesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resumes) {
      ResumeItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResumesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResumesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumes.push(ResumeItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseResumeItem(): ResumeItem {
  return { id: "", title: "", status: "", createdAt: "" };
}

export const ResumeItem: MessageFns<ResumeItem> = {
  encode(message: ResumeItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResumeItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResumeItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetResumeRequest(): GetResumeRequest {
  return { resumeId: "", userId: "" };
}

export const GetResumeRequest: MessageFns<GetResumeRequest> = {
  encode(message: GetResumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resumeId !== "") {
      writer.uint32(10).string(message.resumeId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resumeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetResumeResponse(): GetResumeResponse {
  return { resume: undefined };
}

export const GetResumeResponse: MessageFns<GetResumeResponse> = {
  encode(message: GetResumeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resume !== undefined) {
      ResumeDetail.encode(message.resume, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetResumeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetResumeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resume = ResumeDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseResumeDetail(): ResumeDetail {
  return { id: "", title: "", content: "", status: "", createdAt: "", fileUrl: "" };
}

export const ResumeDetail: MessageFns<ResumeDetail> = {
  encode(message: ResumeDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    if (message.fileUrl !== "") {
      writer.uint32(50).string(message.fileUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResumeDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResumeDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface ResumeServiceClient {
  /** 이력서 업로드 URL 발급 */

  getUploadUrl(request: GetUploadUrlRequest): Observable<GetUploadUrlResponse>;

  /** 이력서 업로드 완료 알림 */

  completeUpload(request: CompleteUploadRequest): Observable<CompleteUploadResponse>;

  /** 사용자 이력서 목록 조회 */

  listResumes(request: ListResumesRequest): Observable<ListResumesResponse>;

  /** 이력서 상세 조회 */

  getResume(request: GetResumeRequest): Observable<GetResumeResponse>;

  /** 이력서 삭제 */

  deleteResume(request: DeleteResumeRequest): Observable<DeleteResumeResponse>;

  /** 이력서 임베딩 목록 조회 (병렬 호출용) */

  getResumeEmbeddings(request: GetResumeEmbeddingsRequest): Observable<GetResumeEmbeddingsResponse>;

  /** 이력서 내용 유효성 검사 (LLM 연동) */

  validateResume(request: ValidateResumeRequest): Observable<ValidateResumeResponse>;
}

export interface ResumeServiceController {
  /** 이력서 업로드 URL 발급 */

  getUploadUrl(
    request: GetUploadUrlRequest,
  ): Promise<GetUploadUrlResponse> | Observable<GetUploadUrlResponse> | GetUploadUrlResponse;

  /** 이력서 업로드 완료 알림 */

  completeUpload(
    request: CompleteUploadRequest,
  ): Promise<CompleteUploadResponse> | Observable<CompleteUploadResponse> | CompleteUploadResponse;

  /** 사용자 이력서 목록 조회 */

  listResumes(
    request: ListResumesRequest,
  ): Promise<ListResumesResponse> | Observable<ListResumesResponse> | ListResumesResponse;

  /** 이력서 상세 조회 */

  getResume(request: GetResumeRequest): Promise<GetResumeResponse> | Observable<GetResumeResponse> | GetResumeResponse;

  /** 이력서 삭제 */

  deleteResume(
    request: DeleteResumeRequest,
  ): Promise<DeleteResumeResponse> | Observable<DeleteResumeResponse> | DeleteResumeResponse;

  /** 이력서 임베딩 목록 조회 (병렬 호출용) */

  getResumeEmbeddings(
    request: GetResumeEmbeddingsRequest,
  ): Promise<GetResumeEmbeddingsResponse> | Observable<GetResumeEmbeddingsResponse> | GetResumeEmbeddingsResponse;

  /** 이력서 내용 유효성 검사 (LLM 연동) */

  validateResume(
    request: ValidateResumeRequest,
  ): Promise<ValidateResumeResponse> | Observable<ValidateResumeResponse> | ValidateResumeResponse;
}

export function ResumeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUploadUrl",
      "completeUpload",
      "listResumes",
      "getResume",
      "deleteResume",
      "getResumeEmbeddings",
      "validateResume",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ResumeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ResumeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RESUME_SERVICE_NAME = "ResumeService";

export type ResumeServiceService = typeof ResumeServiceService;
export const ResumeServiceService = {
  /** 이력서 업로드 URL 발급 */
  getUploadUrl: {
    path: "/resume.ResumeService/GetUploadUrl",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUploadUrlRequest): Buffer => Buffer.from(GetUploadUrlRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadUrlRequest => GetUploadUrlRequest.decode(value),
    responseSerialize: (value: GetUploadUrlResponse): Buffer =>
      Buffer.from(GetUploadUrlResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadUrlResponse => GetUploadUrlResponse.decode(value),
  },
  /** 이력서 업로드 완료 알림 */
  completeUpload: {
    path: "/resume.ResumeService/CompleteUpload",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CompleteUploadRequest): Buffer =>
      Buffer.from(CompleteUploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteUploadRequest => CompleteUploadRequest.decode(value),
    responseSerialize: (value: CompleteUploadResponse): Buffer =>
      Buffer.from(CompleteUploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CompleteUploadResponse => CompleteUploadResponse.decode(value),
  },
  /** 사용자 이력서 목록 조회 */
  listResumes: {
    path: "/resume.ResumeService/ListResumes",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListResumesRequest): Buffer => Buffer.from(ListResumesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListResumesRequest => ListResumesRequest.decode(value),
    responseSerialize: (value: ListResumesResponse): Buffer => Buffer.from(ListResumesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListResumesResponse => ListResumesResponse.decode(value),
  },
  /** 이력서 상세 조회 */
  getResume: {
    path: "/resume.ResumeService/GetResume",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetResumeRequest): Buffer => Buffer.from(GetResumeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetResumeRequest => GetResumeRequest.decode(value),
    responseSerialize: (value: GetResumeResponse): Buffer => Buffer.from(GetResumeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetResumeResponse => GetResumeResponse.decode(value),
  },
  /** 이력서 삭제 */
  deleteResume: {
    path: "/resume.ResumeService/DeleteResume",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteResumeRequest): Buffer => Buffer.from(DeleteResumeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteResumeRequest => DeleteResumeRequest.decode(value),
    responseSerialize: (value: DeleteResumeResponse): Buffer =>
      Buffer.from(DeleteResumeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResumeResponse => DeleteResumeResponse.decode(value),
  },
  /** 이력서 임베딩 목록 조회 (병렬 호출용) */
  getResumeEmbeddings: {
    path: "/resume.ResumeService/GetResumeEmbeddings",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetResumeEmbeddingsRequest): Buffer =>
      Buffer.from(GetResumeEmbeddingsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetResumeEmbeddingsRequest => GetResumeEmbeddingsRequest.decode(value),
    responseSerialize: (value: GetResumeEmbeddingsResponse): Buffer =>
      Buffer.from(GetResumeEmbeddingsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetResumeEmbeddingsResponse => GetResumeEmbeddingsResponse.decode(value),
  },
  /** 이력서 내용 유효성 검사 (LLM 연동) */
  validateResume: {
    path: "/resume.ResumeService/ValidateResume",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateResumeRequest): Buffer =>
      Buffer.from(ValidateResumeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateResumeRequest => ValidateResumeRequest.decode(value),
    responseSerialize: (value: ValidateResumeResponse): Buffer =>
      Buffer.from(ValidateResumeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ValidateResumeResponse => ValidateResumeResponse.decode(value),
  },
} as const;

export interface ResumeServiceServer extends UntypedServiceImplementation {
  /** 이력서 업로드 URL 발급 */
  getUploadUrl: handleUnaryCall<GetUploadUrlRequest, GetUploadUrlResponse>;
  /** 이력서 업로드 완료 알림 */
  completeUpload: handleUnaryCall<CompleteUploadRequest, CompleteUploadResponse>;
  /** 사용자 이력서 목록 조회 */
  listResumes: handleUnaryCall<ListResumesRequest, ListResumesResponse>;
  /** 이력서 상세 조회 */
  getResume: handleUnaryCall<GetResumeRequest, GetResumeResponse>;
  /** 이력서 삭제 */
  deleteResume: handleUnaryCall<DeleteResumeRequest, DeleteResumeResponse>;
  /** 이력서 임베딩 목록 조회 (병렬 호출용) */
  getResumeEmbeddings: handleUnaryCall<GetResumeEmbeddingsRequest, GetResumeEmbeddingsResponse>;
  /** 이력서 내용 유효성 검사 (LLM 연동) */
  validateResume: handleUnaryCall<ValidateResumeRequest, ValidateResumeResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
