// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.4
// source: storage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "storage";

export interface GetPresignedUrlRequest {
  objectKey: string;
  /** "get_object", "put_object" */
  method: string;
  expirationSec: number;
  /** if true, returns internal k8s url */
  internalAccess: boolean;
}

export interface GetPresignedUrlResponse {
  url: string;
}

export interface DeleteObjectRequest {
  objectKey: string;
}

export interface DeleteObjectResponse {
  success: boolean;
  message: string;
}

export const STORAGE_PACKAGE_NAME = "storage";

function createBaseGetPresignedUrlRequest(): GetPresignedUrlRequest {
  return { objectKey: "", method: "", expirationSec: 0, internalAccess: false };
}

export const GetPresignedUrlRequest: MessageFns<GetPresignedUrlRequest> = {
  encode(message: GetPresignedUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.objectKey !== "") {
      writer.uint32(10).string(message.objectKey);
    }
    if (message.method !== "") {
      writer.uint32(18).string(message.method);
    }
    if (message.expirationSec !== 0) {
      writer.uint32(24).int32(message.expirationSec);
    }
    if (message.internalAccess !== false) {
      writer.uint32(32).bool(message.internalAccess);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPresignedUrlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPresignedUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expirationSec = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.internalAccess = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetPresignedUrlResponse(): GetPresignedUrlResponse {
  return { url: "" };
}

export const GetPresignedUrlResponse: MessageFns<GetPresignedUrlResponse> = {
  encode(message: GetPresignedUrlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPresignedUrlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPresignedUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteObjectRequest(): DeleteObjectRequest {
  return { objectKey: "" };
}

export const DeleteObjectRequest: MessageFns<DeleteObjectRequest> = {
  encode(message: DeleteObjectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.objectKey !== "") {
      writer.uint32(10).string(message.objectKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteObjectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteObjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteObjectResponse(): DeleteObjectResponse {
  return { success: false, message: "" };
}

export const DeleteObjectResponse: MessageFns<DeleteObjectResponse> = {
  encode(message: DeleteObjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteObjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteObjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface StorageServiceClient {
  /** 발급된 Presigned URL 요청 */

  getPresignedUrl(request: GetPresignedUrlRequest): Observable<GetPresignedUrlResponse>;

  /** 객체 삭제 요청 */

  deleteObject(request: DeleteObjectRequest): Observable<DeleteObjectResponse>;
}

export interface StorageServiceController {
  /** 발급된 Presigned URL 요청 */

  getPresignedUrl(
    request: GetPresignedUrlRequest,
  ): Promise<GetPresignedUrlResponse> | Observable<GetPresignedUrlResponse> | GetPresignedUrlResponse;

  /** 객체 삭제 요청 */

  deleteObject(
    request: DeleteObjectRequest,
  ): Promise<DeleteObjectResponse> | Observable<DeleteObjectResponse> | DeleteObjectResponse;
}

export function StorageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPresignedUrl", "deleteObject"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STORAGE_SERVICE_NAME = "StorageService";

export type StorageServiceService = typeof StorageServiceService;
export const StorageServiceService = {
  /** 발급된 Presigned URL 요청 */
  getPresignedUrl: {
    path: "/storage.StorageService/GetPresignedUrl",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetPresignedUrlRequest): Buffer =>
      Buffer.from(GetPresignedUrlRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPresignedUrlRequest => GetPresignedUrlRequest.decode(value),
    responseSerialize: (value: GetPresignedUrlResponse): Buffer =>
      Buffer.from(GetPresignedUrlResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetPresignedUrlResponse => GetPresignedUrlResponse.decode(value),
  },
  /** 객체 삭제 요청 */
  deleteObject: {
    path: "/storage.StorageService/DeleteObject",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteObjectRequest): Buffer => Buffer.from(DeleteObjectRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteObjectRequest => DeleteObjectRequest.decode(value),
    responseSerialize: (value: DeleteObjectResponse): Buffer =>
      Buffer.from(DeleteObjectResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteObjectResponse => DeleteObjectResponse.decode(value),
  },
} as const;

export interface StorageServiceServer extends UntypedServiceImplementation {
  /** 발급된 Presigned URL 요청 */
  getPresignedUrl: handleUnaryCall<GetPresignedUrlRequest, GetPresignedUrlResponse>;
  /** 객체 삭제 요청 */
  deleteObject: handleUnaryCall<DeleteObjectRequest, DeleteObjectResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
