// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: user/v1/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user.v1";

export interface FindUserByIdRequest {
  userId: string;
}

export interface FindUserByIdResponse {
  candidate?: Candidate | undefined;
  recruiter?: Recruiter | undefined;
}

export interface FindUserByEmailRequest {
  email: string;
}

export interface FindUserByEmailResponse {
  candidate?: Candidate | undefined;
  recruiter?: Recruiter | undefined;
}

export interface Candidate {
  id: string;
  email: string;
  nickname: string;
  role: string;
  phoneNumber: string;
  verifiedEmail: string;
  passwordHash: string;
}

export interface Recruiter {
  id: string;
  email: string;
  nickname: string;
  role: string;
  phoneNumber: string;
  verifiedEmail: string;
  companyCode: string;
  passwordHash: string;
}

export interface RegisterCandidateRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
}

export interface RegisterRecruiterRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
  companyCode: string;
}

export interface RegisterUserResponse {
  userId: string;
}

export const USER_V1_PACKAGE_NAME = "user.v1";

export interface UserServiceClient {
  findUserById(request: FindUserByIdRequest, metadata?: Metadata): Observable<FindUserByIdResponse>;

  findUserByEmail(request: FindUserByEmailRequest, metadata?: Metadata): Observable<FindUserByEmailResponse>;

  registerCandidate(request: RegisterCandidateRequest, metadata?: Metadata): Observable<RegisterUserResponse>;

  registerRecruiter(request: RegisterRecruiterRequest, metadata?: Metadata): Observable<RegisterUserResponse>;
}

export interface UserServiceController {
  findUserById(
    request: FindUserByIdRequest,
    metadata?: Metadata,
  ): Promise<FindUserByIdResponse> | Observable<FindUserByIdResponse> | FindUserByIdResponse;

  findUserByEmail(
    request: FindUserByEmailRequest,
    metadata?: Metadata,
  ): Promise<FindUserByEmailResponse> | Observable<FindUserByEmailResponse> | FindUserByEmailResponse;

  registerCandidate(
    request: RegisterCandidateRequest,
    metadata?: Metadata,
  ): Promise<RegisterUserResponse> | Observable<RegisterUserResponse> | RegisterUserResponse;

  registerRecruiter(
    request: RegisterRecruiterRequest,
    metadata?: Metadata,
  ): Promise<RegisterUserResponse> | Observable<RegisterUserResponse> | RegisterUserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findUserById", "findUserByEmail", "registerCandidate", "registerRecruiter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
