apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-track1-credentials
  namespace: unbrdn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: redis-track1-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: redis-track1-password
