# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_stream(
                '/llm.LlmService/GenerateResponse',
                request_serializer=llm__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__pb2.TokenChunk.FromString,
                _registered_method=True)
        self.TextToSpeech = channel.unary_stream(
                '/llm.LlmService/TextToSpeech',
                request_serializer=llm__pb2.TTSRequest.SerializeToString,
                response_deserializer=llm__pb2.TTSChunk.FromString,
                _registered_method=True)
        self.ClassifyResume = channel.unary_unary(
                '/llm.LlmService/ClassifyResume',
                request_serializer=llm__pb2.ClassifyResumeRequest.SerializeToString,
                response_deserializer=llm__pb2.ClassifyResumeResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/llm.LlmService/GetEmbedding',
                request_serializer=llm__pb2.GetEmbeddingRequest.SerializeToString,
                response_deserializer=llm__pb2.GetEmbeddingResponse.FromString,
                _registered_method=True)


class LlmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=llm__pb2.GenerateRequest.FromString,
                    response_serializer=llm__pb2.TokenChunk.SerializeToString,
            ),
            'TextToSpeech': grpc.unary_stream_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=llm__pb2.TTSRequest.FromString,
                    response_serializer=llm__pb2.TTSChunk.SerializeToString,
            ),
            'ClassifyResume': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyResume,
                    request_deserializer=llm__pb2.ClassifyResumeRequest.FromString,
                    response_serializer=llm__pb2.ClassifyResumeResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=llm__pb2.GetEmbeddingRequest.FromString,
                    response_serializer=llm__pb2.GetEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.LlmService/GenerateResponse',
            llm__pb2.GenerateRequest.SerializeToString,
            llm__pb2.TokenChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.LlmService/TextToSpeech',
            llm__pb2.TTSRequest.SerializeToString,
            llm__pb2.TTSChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/ClassifyResume',
            llm__pb2.ClassifyResumeRequest.SerializeToString,
            llm__pb2.ClassifyResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/GetEmbedding',
            llm__pb2.GetEmbeddingRequest.SerializeToString,
            llm__pb2.GetEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
