# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"\x86\x02\n\x0fGenerateRequest\x12\x14\n\x0cinterview_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tuser_text\x18\x03 \x01(\t\x12\x0f\n\x07persona\x18\x04 \x01(\t\x12)\n\x07history\x18\x05 \x03(\x0b\x32\x18.llm.ConversationHistory\x12\'\n\x05stage\x18\x06 \x01(\x0e\x32\x18.llm.InterviewStageProto\x12\x1e\n\x11interviewer_count\x18\x07 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06\x64omain\x18\x08 \x01(\tH\x01\x88\x01\x01\x42\x14\n\x12_interviewer_countB\t\n\x07_domain\"4\n\x13\x43onversationHistory\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"X\n\nTokenChunk\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x17\n\x0fis_sentence_end\x18\x03 \x01(\x08\x12\x10\n\x08thinking\x18\x04 \x01(\t\"H\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0f\n\x07persona\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x01\"0\n\x08TTSChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08is_final\x18\x02 \x01(\x08*\x98\x01\n\x13InterviewStageProto\x12\x0b\n\x07WAITING\x10\x00\x12\x13\n\x0fGREETING_PROMPT\x10\x01\x12\x0c\n\x08GREETING\x10\x02\x12\x15\n\x11INTERVIEWER_INTRO\x10\x03\x12\x0e\n\nSELF_INTRO\x10\x04\x12\x15\n\x11IN_PROGRESS_STAGE\x10\x05\x12\x13\n\x0f\x43OMPLETED_STAGE\x10\x06\x32{\n\nLlmService\x12;\n\x10GenerateResponse\x12\x14.llm.GenerateRequest\x1a\x0f.llm.TokenChunk0\x01\x12\x30\n\x0cTextToSpeech\x12\x0f.llm.TTSRequest\x1a\r.llm.TTSChunk0\x01\x42#\n\x17me.unbrdn.core.grpc.llmB\x08LlmProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027me.unbrdn.core.grpc.llmB\010LlmProto'
  _globals['_INTERVIEWSTAGEPROTO']._serialized_start=552
  _globals['_INTERVIEWSTAGEPROTO']._serialized_end=704
  _globals['_GENERATEREQUEST']._serialized_start=19
  _globals['_GENERATEREQUEST']._serialized_end=281
  _globals['_CONVERSATIONHISTORY']._serialized_start=283
  _globals['_CONVERSATIONHISTORY']._serialized_end=335
  _globals['_TOKENCHUNK']._serialized_start=337
  _globals['_TOKENCHUNK']._serialized_end=425
  _globals['_TTSREQUEST']._serialized_start=427
  _globals['_TTSREQUEST']._serialized_end=499
  _globals['_TTSCHUNK']._serialized_start=501
  _globals['_TTSCHUNK']._serialized_end=549
  _globals['_LLMSERVICE']._serialized_start=706
  _globals['_LLMSERVICE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
