CREATE TABLE job_field (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT job_field_pkey PRIMARY KEY (id)
);

CREATE TABLE skills (
    id uuid NOT NULL,
    name character varying(50) NOT NULL,
    category character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT skills_pkey PRIMARY KEY (id),
    CONSTRAINT skills_name_key UNIQUE (name)
);

CREATE TABLE user_skills (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    skill_id uuid NOT NULL,
    proficiency_level integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT user_skills_pkey PRIMARY KEY (id),
    CONSTRAINT user_skills_user_id_skill_id_key UNIQUE (user_id, skill_id),
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE TABLE career (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    job_field_id uuid NOT NULL,
    company_name character varying(255) NOT NULL,
    department character varying(255),
    description text,
    started_at date NOT NULL,
    ended_at date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT career_pkey PRIMARY KEY (id),
    CONSTRAINT fk_career_job_field FOREIGN KEY (job_field_id) REFERENCES job_field (id)
);

CREATE TABLE candidate_desire_job_field (
    candidate_id uuid NOT NULL,
    job_field_id uuid NOT NULL,
    CONSTRAINT candidate_desire_job_field_pkey PRIMARY KEY (candidate_id, job_field_id),
    CONSTRAINT fk_cddjf_job_field FOREIGN KEY (job_field_id) REFERENCES job_field (id)
);

CREATE TABLE interview_session (
    id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    resume_id uuid,
    company_name character varying(255),
    type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    domain character varying(100) NOT NULL,
    scheduled_duration_minutes integer NOT NULL,
    turn_count INTEGER NOT NULL DEFAULT 0,
    participating_personas jsonb,
    version BIGINT DEFAULT 0 NOT NULL,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT interview_session_pkey PRIMARY KEY (id)
);


CREATE TABLE interview_adjustment_log (
    id uuid NOT NULL,
    interview_id uuid NOT NULL,
    adjustment_type character varying(50) NOT NULL,
    old_value text,
    new_value text,
    reason text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT interview_adjustment_log_pkey PRIMARY KEY (id),
    CONSTRAINT fk_adjustment_log_session FOREIGN KEY (interview_id) REFERENCES interview_session (id)
);
CREATE INDEX idx_interview_adjustment_log_interview_id ON interview_adjustment_log(interview_id);

CREATE TABLE interview_messages (
    id UUID PRIMARY KEY,
    interview_session_id UUID NOT NULL REFERENCES interview_session(id) ON DELETE CASCADE,
    turn_count INT NOT NULL,
    sequence_number INT NOT NULL,
    role VARCHAR(50) NOT NULL,
    stage VARCHAR(50),
    difficulty_level INT,
    persona_id VARCHAR(50),
    content TEXT,
    media_url VARCHAR(2048),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_interview_messages_session_id_turn_sequence ON interview_messages(interview_session_id, turn_count, sequence_number);

CREATE TABLE interview_history (
    id uuid NOT NULL,
    user_name character varying(255),
    user_question text,
    ai_response text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT interview_history_pkey PRIMARY KEY (id)
);

CREATE TABLE interview_reports (
    id uuid NOT NULL,
    interview_id uuid NOT NULL,
    total_score integer NOT NULL,
    pass_fail_status character varying(10) NOT NULL,
    summary_text text,
    resume_feedback text,
    detail_metrics jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT interview_reports_pkey PRIMARY KEY (id),
    CONSTRAINT interview_reports_interview_id_key UNIQUE (interview_id),
    CONSTRAINT fk_interview_reports_session FOREIGN KEY (interview_id) REFERENCES interview_session (id)
);

CREATE TABLE interview_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    interview_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    user_answer text,
    ai_answer text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT interview_results_pkey PRIMARY KEY (id)
);

CREATE TABLE interview_state_snapshot (
    id uuid NOT NULL,
    interview_session_id uuid NOT NULL,
    state_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT interview_state_snapshot_pkey PRIMARY KEY (id),
    CONSTRAINT fk_interview_snapshot_session FOREIGN KEY (interview_session_id) REFERENCES interview_session (id) ON DELETE CASCADE
);

CREATE INDEX idx_interview_state_snapshot_session_id ON interview_state_snapshot(interview_session_id);
