apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: unbrdn
  labels:
    environment: prod
data:
  redis-host: "redis"
  redis-port: "6379"
  kafka-broker: "kafka-cluster-kafka-bootstrap.kafka:9092"
  python-worker-url: "http://inference:8000"
  core-grpc-host: "core"
  core-grpc-port: "9090"
