apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: unbrdn
  labels:
    app: bff
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
        environment: local
    spec:
      containers:
        - name: bff
          image: bff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: KAFKA_BROKER
              value: kafka:29092
            - name: PYTHON_WORKER_URL
              value: http://inference:8000
            - name: CORE_GRPC_HOST
              value: core
            - name: CORE_GRPC_PORT
              value: "9090"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always

