# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindUserById = channel.unary_unary(
                '/user.v1.UserService/FindUserById',
                request_serializer=user_dot_v1_dot_user__pb2.FindUserByIdRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.FindUserByIdResponse.FromString,
                _registered_method=True)
        self.FindUserByEmail = channel.unary_unary(
                '/user.v1.UserService/FindUserByEmail',
                request_serializer=user_dot_v1_dot_user__pb2.FindUserByEmailRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.FindUserByEmailResponse.FromString,
                _registered_method=True)
        self.RegisterCandidate = channel.unary_unary(
                '/user.v1.UserService/RegisterCandidate',
                request_serializer=user_dot_v1_dot_user__pb2.RegisterCandidateRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.RegisterUserResponse.FromString,
                _registered_method=True)
        self.RegisterRecruiter = channel.unary_unary(
                '/user.v1.UserService/RegisterRecruiter',
                request_serializer=user_dot_v1_dot_user__pb2.RegisterRecruiterRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.RegisterUserResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRecruiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUserById,
                    request_deserializer=user_dot_v1_dot_user__pb2.FindUserByIdRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.FindUserByIdResponse.SerializeToString,
            ),
            'FindUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUserByEmail,
                    request_deserializer=user_dot_v1_dot_user__pb2.FindUserByEmailRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.FindUserByEmailResponse.SerializeToString,
            ),
            'RegisterCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCandidate,
                    request_deserializer=user_dot_v1_dot_user__pb2.RegisterCandidateRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.RegisterUserResponse.SerializeToString,
            ),
            'RegisterRecruiter': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRecruiter,
                    request_deserializer=user_dot_v1_dot_user__pb2.RegisterRecruiterRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.RegisterUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/FindUserById',
            user_dot_v1_dot_user__pb2.FindUserByIdRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.FindUserByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/FindUserByEmail',
            user_dot_v1_dot_user__pb2.FindUserByEmailRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.FindUserByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/RegisterCandidate',
            user_dot_v1_dot_user__pb2.RegisterCandidateRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterRecruiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/RegisterRecruiter',
            user_dot_v1_dot_user__pb2.RegisterRecruiterRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
