// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: auth/v1/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth.v1";

export interface RegisterCandidateRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
}

export interface RegisterRecruiterRequest {
  email: string;
  password: string;
  nickname: string;
  phoneNumber: string;
  companyCode: string;
}

export interface RegisterResponse {
  userId: string;
}

export interface AuthenticateUserRequest {
  email: string;
  password: string;
}

export interface AuthenticateUserResponse {
  accessToken: string;
  refreshToken: string;
  user: User | undefined;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
}

export interface User {
  id: string;
  email: string;
  nickname: string;
  role: string;
  phoneNumber: string;
  companyCode: string;
}

export interface LoginWithOAuthRequest {
  provider: string;
  providerUserId: string;
  accessToken: string;
  tokenExpiresAt: number;
  email: string;
  name: string;
  pictureUrl: string;
}

export interface LoginWithOAuthResponse {
  isNewUser: boolean;
  pendingToken: string;
  auth: AuthenticateUserResponse | undefined;
}

export interface CompleteOAuthProfileRequest {
  pendingToken: string;
  role: string;
  phoneNumber: string;
  nickname: string;
  password: string;
}

export const AUTH_V1_PACKAGE_NAME = "auth.v1";

export interface AuthServiceClient {
  registerCandidate(request: RegisterCandidateRequest, metadata?: Metadata): Observable<RegisterResponse>;

  registerRecruiter(request: RegisterRecruiterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  authenticateUser(request: AuthenticateUserRequest, metadata?: Metadata): Observable<AuthenticateUserResponse>;

  refreshToken(request: RefreshTokenRequest, metadata?: Metadata): Observable<RefreshTokenResponse>;

  loginWithOAuth(request: LoginWithOAuthRequest, metadata?: Metadata): Observable<LoginWithOAuthResponse>;

  completeOAuthProfile(request: CompleteOAuthProfileRequest, metadata?: Metadata): Observable<AuthenticateUserResponse>;
}

export interface AuthServiceController {
  registerCandidate(
    request: RegisterCandidateRequest,
    metadata?: Metadata,
  ): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  registerRecruiter(
    request: RegisterRecruiterRequest,
    metadata?: Metadata,
  ): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  authenticateUser(
    request: AuthenticateUserRequest,
    metadata?: Metadata,
  ): Promise<AuthenticateUserResponse> | Observable<AuthenticateUserResponse> | AuthenticateUserResponse;

  refreshToken(
    request: RefreshTokenRequest,
    metadata?: Metadata,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;

  loginWithOAuth(
    request: LoginWithOAuthRequest,
    metadata?: Metadata,
  ): Promise<LoginWithOAuthResponse> | Observable<LoginWithOAuthResponse> | LoginWithOAuthResponse;

  completeOAuthProfile(
    request: CompleteOAuthProfileRequest,
    metadata?: Metadata,
  ): Promise<AuthenticateUserResponse> | Observable<AuthenticateUserResponse> | AuthenticateUserResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "registerCandidate",
      "registerRecruiter",
      "authenticateUser",
      "refreshToken",
      "loginWithOAuth",
      "completeOAuthProfile",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
