apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: unbrdn
  labels:
    environment: prod
data:
  # Oracle Autonomous Database URL
  # 형식: jdbc:oracle:thin:@<host>:<port>/<service_name>
  # 예시: jdbc:oracle:thin:@adb.ap-chuncheon-1.oraclecloud.com:1522/gf042308c5c1882_unbrdn0krn0db_high.adb.oraclecloud.com
  datasource-url: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=adb.ap-chuncheon-1.oraclecloud.com)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=gf042308c5c1882_unbrdn0krn0db_high.adb.oraclecloud.com))(SECURITY=(SSL_SERVER_DN_MATCH=YES)))"
  kafka-bootstrap-servers: "kafka-cluster-kafka-bootstrap.kafka:9092"
