apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: unbrdn
  labels:
    app: core
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
        environment: local
    spec:
      containers:
        - name: core
          image: core:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/interview_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
