apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  namespace: unbrdn
  labels:
    app: inference
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
        environment: local
    spec:
      containers:
        - name: inference
          image: inference:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: inference-secrets
            - configMapRef:
                name: inference-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
