apiVersion: v1
kind: Service
metadata:
  name: inference
  namespace: unbrdn
  labels:
    app: inference
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: inference

