apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: unbrdn
  labels:
    app: socket
    environment: prod
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
        environment: prod
    spec:
      # 고가용성(HA): Socket을 최대한 넓게 분산 배치
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: socket
      # Preemptible 노드 회피 (안정성 확보)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: socket
                topologyKey: kubernetes.io/hostname


      imagePullSecrets:


        - name: acr-secret


      containers:
        - name: socket
          image: unbrdnacr.azurecr.io/socket:ef844a9ccfd3dd3925bc593345a6e0530ff4998d
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
            initialDelaySeconds: 25
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: REDIS_PASSWORD
              value: ""
          envFrom:
            - configMapRef:
                name: socket-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
