apiVersion: v1
kind: ResourceQuota
metadata:
  name: inference-quota
  namespace: inference
spec:
  hard:
    requests.cpu: "3"
    limits.cpu: "6"
    requests.memory: 6Gi
    limits.memory: 10Gi
    pods: "5"
