apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: unbrdn
  labels:
    app: socket
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
        environment: local
    spec:
      containers:
        - name: socket
          image: socket:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: socket-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always

