apiVersion: v1
kind: Service
metadata:
  name: socket
  namespace: unbrdn
  labels:
    app: socket
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: socket

