// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: storage/v1/storage.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "storage.v1";

export interface GetPresignedUrlRequest {
  objectKey: string;
  /** "GET", "PUT", "DELETE" */
  method: string;
  expirationSec: number;
  internalAccess: boolean;
}

export interface GetPresignedUrlResponse {
  url: string;
}

export interface DeleteObjectRequest {
  objectKey: string;
}

export interface DeleteObjectResponse {
  success: boolean;
  message: string;
}

export const STORAGE_V1_PACKAGE_NAME = "storage.v1";

export interface StorageServiceClient {
  /** Get presigned URL for upload/download */

  getPresignedUrl(request: GetPresignedUrlRequest, metadata?: Metadata): Observable<GetPresignedUrlResponse>;

  /** Delete object from storage */

  deleteObject(request: DeleteObjectRequest, metadata?: Metadata): Observable<DeleteObjectResponse>;
}

export interface StorageServiceController {
  /** Get presigned URL for upload/download */

  getPresignedUrl(
    request: GetPresignedUrlRequest,
    metadata?: Metadata,
  ): Promise<GetPresignedUrlResponse> | Observable<GetPresignedUrlResponse> | GetPresignedUrlResponse;

  /** Delete object from storage */

  deleteObject(
    request: DeleteObjectRequest,
    metadata?: Metadata,
  ): Promise<DeleteObjectResponse> | Observable<DeleteObjectResponse> | DeleteObjectResponse;
}

export function StorageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPresignedUrl", "deleteObject"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StorageService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STORAGE_SERVICE_NAME = "StorageService";
