// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: llm/v1/llm.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { InterviewStageProto } from "../../common/v1/enums";

export const protobufPackage = "llm.v1";

export interface ClassifyResumeRequest {
  text: string;
}

export interface ClassifyResumeResponse {
  isResume: boolean;
  reason: string;
  score: number;
}

export interface GetEmbeddingRequest {
  text: string;
}

export interface GetEmbeddingResponse {
  embedding: number[];
}

export interface PersonaProfile {
  id: string;
  /** e.g. "Tech Interviewer" */
  name: string;
  /** e.g. "MAIN", "SUPPORT" */
  role: string;
  /** e.g. "Sharp", "Encouraging" */
  tone: string;
}

export interface GenerateRequest {
  interviewId: string;
  userId: string;
  userText: string;
  participatingPersonas: string[];
  stage: InterviewStageProto;
  domain?: string | undefined;
  remainingTimeSeconds: number;
  scheduledDurationMinutes: number;
  currentDifficultyLevel: number;
  lastInterviewerId: string;
  companyName: string;
  /** "user" (default) or "system" */
  inputRole: string;
  /** 면접관 페르소나 템플릿 렌더링용 식별자 */
  personaId: string;
  /** 이력서 IDe */
  resumeId: string;
}

export interface TokenChunk {
  token: string;
  isFinal: boolean;
  isSentenceEnd: boolean;
  /** LangGraph 노드 실행 정보 */
  thinking: string;
  /** 발화자 ID */
  currentPersonaId: string;
  /** 조정된 다음 난이도 */
  nextDifficultyLevel: number;
  /** 전체 시간 20% 단축 신호 */
  reduceTotalTime: boolean;
  /** 면접 종료 신호 */
  interviewEndSignal: boolean;
}

export interface TTSRequest {
  text: string;
  mode: string;
  persona: string;
  speed: number;
}

export interface TTSChunk {
  audioData: Uint8Array;
  isFinal: boolean;
}

export const LLM_V1_PACKAGE_NAME = "llm.v1";

export interface LlmServiceClient {
  generateResponse(request: GenerateRequest, metadata?: Metadata): Observable<TokenChunk>;

  textToSpeech(request: TTSRequest, metadata?: Metadata): Observable<TTSChunk>;

  getEmbedding(request: GetEmbeddingRequest, metadata?: Metadata): Observable<GetEmbeddingResponse>;

  /** 이력서 분류 및 판별 */

  classifyResume(request: ClassifyResumeRequest, metadata?: Metadata): Observable<ClassifyResumeResponse>;
}

export interface LlmServiceController {
  generateResponse(request: GenerateRequest, metadata?: Metadata): Observable<TokenChunk>;

  textToSpeech(request: TTSRequest, metadata?: Metadata): Observable<TTSChunk>;

  getEmbedding(
    request: GetEmbeddingRequest,
    metadata?: Metadata,
  ): Promise<GetEmbeddingResponse> | Observable<GetEmbeddingResponse> | GetEmbeddingResponse;

  /** 이력서 분류 및 판별 */

  classifyResume(
    request: ClassifyResumeRequest,
    metadata?: Metadata,
  ): Promise<ClassifyResumeResponse> | Observable<ClassifyResumeResponse> | ClassifyResumeResponse;
}

export function LlmServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generateResponse", "textToSpeech", "getEmbedding", "classifyResume"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LlmService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LlmService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LLM_SERVICE_NAME = "LlmService";
