apiVersion: v1
kind: ConfigMap
metadata:
  name: socket-config
  namespace: unbrdn
  labels:
    app: socket
data:
  PORT: "4000"

  REDIS_SENTINEL_HOSTS: "redis-track1-node-0.redis-track1-headless.unbrdn.svc.cluster.local:26379,redis-track1-node-1.redis-track1-headless.unbrdn.svc.cluster.local:26379"
  REDIS_SENTINEL_HOST: "redis-track1-node-0.redis-track1-headless.unbrdn.svc.cluster.local"
  REDIS_SENTINEL_PORT: "26379"
  REDIS_SENTINEL_NAME: "mymaster"
  REDIS_DB: "0"
  REDIS_HOST: "redis-track1.unbrdn.svc.cluster.local"
  REDIS_PORT: "6379"

  KAFKA_BROKER: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  STT_GRPC_HOST: "stt.unbrdn.svc.cluster.local"
  STT_GRPC_PORT: "50052"
  CORE_GRPC_HOST: "core.unbrdn.svc.cluster.local"
  CORE_GRPC_PORT: "9090"

  AUTH_GRPC_HOST: "auth.unbrdn.svc.cluster.local"
  AUTH_GRPC_PORT: "9090"
  INTERVIEW_GRPC_HOST: "interview.unbrdn.svc.cluster.local"
  INTERVIEW_GRPC_PORT: "9090"
  PAYMENT_GRPC_HOST: "payment.unbrdn.svc.cluster.local"
  PAYMENT_GRPC_PORT: "9090"
  RESUME_GRPC_HOST: "resume.unbrdn.svc.cluster.local"
  RESUME_GRPC_PORT: "9090"

  JWT_JWKS_URI: "http://auth.unbrdn.svc.cluster.local:8081/.well-known/jwks.json"
  JWT_JWKS_CACHE_MAX_AGE_MS: "300000"
  JWT_JWKS_REQUESTS_PER_MINUTE: "10"
  JWT_JWKS_TIMEOUT_MS: "30000"
