apiVersion: v2
name: redis-track1
description: Track 1 Redis (Sentinel Mode, Pub/Sub, Buffer)
type: application
version: 0.1.0
appVersion: "7.4.1"

dependencies:
  - name: redis
    version: "20.6.0" # Bitnami Redis stable (Redis 7.4.x)
    repository: "https://charts.bitnami.com/bitnami"
