# ===============================
# Track 1 Redis: Sentinel Mode (Bitnami)
# ===============================
image:
  registry: docker.io
  repository: bitnami/redis
  tag: "7.2.4-debian-12-r22" # 👈 실존하는 최신 전압 고정

sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: "7.2.4-debian-12-r19" # 👈 실존하는 최신 전압 고정

auth:
  enabled: true
  password: "SecureTrack1Password"

master:
  nodeSelector:
    role: app
  persistence:
    enabled: false

replica:
  nodeSelector:
    role: app
  persistence:
    enabled: false
