name: 🔐 Deploy Payment Service

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'services/domains/payment/**'
      - '.github/workflows/deploy-payment.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "payment"
      service_path: "./services/domains/payment"
      helm_values_path: "./k8s/apps/payment/values.yaml"
    secrets:
      inherit
