name: 🔐 Deploy Storage Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/infra/storage/**'
      - '.github/workflows/deploy-storage.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "storage"
      service_path: "./services/infra/storage"
      helm_values_path: "./k8s/apps/storage/prod/deployment.yaml"
    secrets:
      inherit
