name: 🔐 Deploy Interview Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/domains/interview/**'
      - '.github/workflows/deploy-interview.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "interview"
      service_path: "./services/domains/interview"
      helm_values_path: "./k8s/apps/interview/values.yaml"
    secrets:
      inherit
