name: 🔐 Deploy Socket Service

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'services/gateways/socket/**'
      - '.github/workflows/deploy-socket.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "socket"
      service_path: "./services/gateways/socket"
      helm_values_path: "./k8s/apps/socket/prod/deployment.yaml"
    secrets:
      inherit
