name: 🔐 Deploy BFF Service

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'services/gateways/bff/**'
      - '.github/workflows/deploy-bff.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "bff"
      service_path: "./services/gateways/bff"
      helm_values_path: "./k8s/apps/bff/prod/deployment.yaml"
    secrets:
      inherit
