name: 🔐 Deploy STT Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/infra/stt/**'
      - '.github/workflows/deploy-stt.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "stt"
      service_path: "./services/infra/stt"
      helm_values_path: "./k8s/apps/stt/values.yaml"
    secrets:
      inherit
