name: 🔐 Deploy TTS Service

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'services/infra/tts/**'
      - '.github/workflows/deploy-tts.yml'

jobs:
  call-builder:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "tts"
      service_path: "./services/infra/tts"
      helm_values_path: "./k8s/apps/tts/prod/deployment.yaml"
    secrets:
      inherit
